# Generated by Django 6.0.2 on 2026-04-13 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_shopware_image_sync_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('introduction', models.TextField(blank=True, verbose_name='Einleitung')),
                ('full_mjml', models.TextField(blank=True, editable=False, verbose_name='MJML')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
            ],
            options={
                'verbose_name': 'E-Mail',
                'verbose_name_plural': 'E-Mails',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('header', models.CharField(blank=True, help_text='Optional. Wird als Trennüberschrift zwischen Produktgruppen angezeigt.', max_length=255, verbose_name='Abschnitts-Header')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Position')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='emails.email', verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'Abschnitt',
                'verbose_name_plural': 'Abschnitte',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='EmailSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Überschreibt den regulären Preis des Produkts für diese E-Mail.', max_digits=10, null=True, verbose_name='Sonderpreis')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_section_products', to='products.product', verbose_name='Produkt')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='emails.emailsection', verbose_name='Abschnitt')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'ordering': ('position',),
            },
        ),
    ]
