# Generated by Django 6.0.2 on 2026-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsectionproduct',
            name='special_price',
        ),
        migrations.AddField(
            model_name='emailsectionproduct',
            name='special_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prozentualer Rabatt auf den Standardpreis für diese E-Mail, z.B. 10.00 für 10%.', max_digits=5, null=True, verbose_name='Rabatt (%)'),
        ),
    ]
