# Generated by Django 6.0.2 on 2026-06-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('shopware', '0004_shopwareconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaignsaleschannel',
            options={'ordering': ('-sales_channel__is_default', 'sales_channel__name'), 'verbose_name': 'Kampagnen-Sales-Channel', 'verbose_name_plural': 'Kampagnen-Sales-Channels'},
        ),
        migrations.AlterField(
            model_name='emailcampaignsaleschannel',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopware.shopwaresettings', verbose_name='Sales Channel'),
        ),
    ]
