# Generated by Django 6.0.2 on 2026-04-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emailsectionproduct_special_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsectionproduct',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Berechneter Sonderpreis'),
        ),
    ]
