# Generated by Django 6.0.2 on 2026-06-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailsectionproduct_special_price'),
        ('products', '0030_delete_prices_without_sales_channel'),
        ('shopware', '0004_shopwareconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('internal_title', models.CharField(help_text='Wird nicht in der E-Mail angezeigt.', max_length=255, verbose_name='Interner Titel')),
                ('h1', models.CharField(max_length=255, verbose_name='Hauptüberschrift')),
                ('h1_small', models.CharField(blank=True, default='', max_length=255, verbose_name='Untertitel')),
                ('intro_text', models.TextField(blank=True, default='', help_text='HTML erlaubt. Wird zwischen Anrede und Produkt-Listing angezeigt.', verbose_name='Einleitungstext')),
                ('product_template', models.CharField(choices=[('product', 'Standard'), ('product_shipping_free', 'Kostenloser Versand'), ('product_green', 'Grün')], default='product', max_length=30, verbose_name='Produkt-Template')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Bereit'), ('exported', 'Exportiert')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'E-Mail Kampagne',
                'verbose_name_plural': 'E-Mail Kampagnen',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='emailsection',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailsectionproduct',
            name='section',
        ),
        migrations.RemoveField(
            model_name='emailsectionproduct',
            name='product',
        ),
        migrations.CreateModel(
            name='EmailCampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('special_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Überschreibt den Sonderpreis des Produkts für diese Kampagne.', max_digits=10, null=True, verbose_name='Sonderpreis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='emails.emailcampaign', verbose_name='Kampagne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaign_products', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Kampagnen-Produkt',
                'verbose_name_plural': 'Kampagnen-Produkte',
                'ordering': ('order', 'id'),
                'unique_together': {('campaign', 'product')},
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignSalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('enabled', models.BooleanField(default=False, verbose_name='Aktiviert')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='emails.emailcampaign', verbose_name='Kampagne')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopware.shopwaresettings', verbose_name='Sales Channel')),
            ],
            options={
                'verbose_name': 'Kampagnen-Sales-Channel',
                'verbose_name_plural': 'Kampagnen-Sales-Channels',
                'ordering': ('-sales_channel__is_default', 'sales_channel__name'),
                'unique_together': {('campaign', 'sales_channel')},
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailSection',
        ),
        migrations.DeleteModel(
            name='EmailSectionProduct',
        ),
    ]
