# Generated by Django 6.0.2 on 2026-06-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_replace_legacy_email_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('component_key', models.CharField(choices=[('header_nav', 'Onlineansicht & Navigation'), ('logo', 'Logo'), ('title_intro', 'Ueberschrift & Einleitung'), ('products', 'Produkte'), ('content_text', 'Textblock'), ('blog_acymailing', 'Blog Auto-Content'), ('certs_logo_green', 'Zertifikate gruen'), ('4r', '4R Nachhaltigkeit'), ('weihnachten', 'Weihnachten'), ('contact_table', 'Kontaktformular'), ('disclaimer', 'Disclaimer')], max_length=40, verbose_name='Komponente')),
                ('title', models.CharField(blank=True, default='', help_text='Interner Name oder Ueberschrift fuer Textbloecke.', max_length=255, verbose_name='Titel')),
                ('body_html', models.TextField(blank=True, default='', help_text='HTML erlaubt. Wird fuer bearbeitbare Text-Komponenten verwendet.', verbose_name='Inhalt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktiviert')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='emails.emailcampaign', verbose_name='Kampagne')),
            ],
            options={
                'verbose_name': 'Kampagnen-Komponente',
                'verbose_name_plural': 'Kampagnen-Komponenten',
                'ordering': ('order', 'id'),
            },
        ),
    ]
