# Generated by Django 6.0.2 on 2026-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_campaign_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='mjml_markup',
            field=models.TextField(blank=True, default='', help_text='MJML Vorlage dieser Komponente. Django-Template-Variablen sind erlaubt.', verbose_name='MJML Markup'),
        ),
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Untertitel'),
        ),
    ]
