# Generated by Django 6.0.2 on 2026-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_component_markup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hauptüberschrift'),
        ),
    ]
