# Generated by Django 6.0.2 on 2026-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_make_legacy_campaign_title_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='MjmlComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('mjml_markup', models.TextField(blank=True, default='', verbose_name='MJML Markup')),
                ('placement', models.CharField(choices=[('head', 'Head'), ('body', 'Body')], default='body', max_length=10, verbose_name='Platzierung')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'MJML Komponente',
                'verbose_name_plural': 'MJML Komponenten',
                'ordering': ('order', 'name'),
            },
        ),
    ]
