# Generated by Django 6.0.2 on 2026-06-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_mjml_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='library_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_usages', to='emails.mjmlcomponent', verbose_name='Bibliotheks-Komponente'),
        ),
        migrations.AlterField(
            model_name='mjmlcomponent',
            name='mjml_markup',
            field=models.TextField(blank=True, default='', verbose_name='MJML-Markup'),
        ),
        migrations.AlterField(
            model_name='mjmlcomponent',
            name='placement',
            field=models.CharField(choices=[('head', 'Head (Kopfbereich)'), ('body', 'Body (Inhaltsbereich)')], default='body', max_length=10, verbose_name='Platzierung'),
        ),
    ]
