# Generated by Django 6.0.2 on 2026-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_add_library_component_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaignproduct',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alternativ zum absoluten Sonderpreis. Wird auf den Standardkanalpreis angewendet.', max_digits=5, null=True, verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='emailcampaignproduct',
            name='prices_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Preise synchronisiert am'),
        ),
    ]
