# Generated by Django 6.0.2 on 2026-06-17 08:46

import os
from django.db import migrations


LEGACY_COMPONENT_ENTRIES = [
    # (component_key, display_name, placement, is_default, order)
    ("header_nav",       "Onlineansicht & Navigation",    "body", True,  10),
    ("logo",             "Logo",                          "body", True,  20),
    ("title_intro",      "Überschrift & Einleitung",      "body", True,  30),
    ("products",         "Produkte Standard",             "body", True,  40),
    ("product_shipping_free", "Produkte Kostenloser Versand", "body", False, 41),
    ("product_green",    "Produkte Grün",                 "body", False, 42),
    ("content_text",     "Textblock",                     "body", False, 50),
    ("blog_acymailing",  "Blog Auto-Content",             "body", False, 60),
    ("certs_logo_green", "Zertifikate grün",              "body", False, 70),
    ("4r",               "4R Nachhaltigkeit",             "body", False, 80),
    ("weihnachten",      "Weihnachten",                   "body", False, 90),
    ("contact_table",    "Kontaktformular",               "body", True, 100),
    ("disclaimer",       "Disclaimer",                   "body", True, 110),
    ("head",             "Head (CSS & Meta)",             "head", True,   5),
]

LEGACY_TEMPLATE_FILE_MAP = {
    "header_nav":            "legacy/header_nav.mjml",
    "logo":                  "legacy/logo.mjml",
    "title_intro":           "legacy/title_intro.mjml",
    "products":              "legacy/products.mjml",
    "product_shipping_free": "legacy/products.mjml",
    "product_green":         "legacy/products.mjml",
    "content_text":          "legacy/content_text.mjml",
    "blog_acymailing":       "legacy/blog_acymailing.mjml",
    "certs_logo_green":      "legacy/certs_logo_green.mjml",
    "4r":                    "legacy/4r.mjml",
    "weihnachten":           "legacy/weihnachten.mjml",
    "contact_table":         "legacy/contact_table.mjml",
    "disclaimer":            "legacy/disclaimer.mjml",
    "head":                  "head.mjml",
}

PRODUCT_TEMPLATE_TO_KEY = {
    "product":              "products",
    "product_shipping_free": "product_shipping_free",
    "product_green":        "product_green",
}


def _read_template(key: str) -> str:
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    rel = LEGACY_TEMPLATE_FILE_MAP.get(key, "")
    if not rel:
        return ""
    path = os.path.join(base, "templates", "emails", "components", rel)
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return f.read()
    return ""


def forwards(apps, schema_editor):
    MjmlComponent = apps.get_model("emails", "MjmlComponent")
    EmailCampaignComponent = apps.get_model("emails", "EmailCampaignComponent")
    EmailCampaign = apps.get_model("emails", "EmailCampaign")

    # 1. Create library entries
    lib_by_key = {}
    for key, name, placement, is_default, order in LEGACY_COMPONENT_ENTRIES:
        obj, _ = MjmlComponent.objects.get_or_create(
            name=name,
            defaults={
                "mjml_markup": _read_template(key),
                "placement": placement,
                "is_default": is_default,
                "order": order,
            },
        )
        lib_by_key[key] = obj

    # 2. Link existing EmailCampaignComponent rows
    for comp in EmailCampaignComponent.objects.select_related("campaign").all():
        component_key = comp.component_key
        if component_key == "products":
            pt = getattr(comp.campaign, "product_template", "product") or "product"
            mapped_key = PRODUCT_TEMPLATE_TO_KEY.get(pt, "products")
        else:
            mapped_key = component_key
        lib = lib_by_key.get(mapped_key)
        if lib:
            comp.library_component = lib
            comp.save(update_fields=["library_component"])

    # 3. Move h1/h1_small/intro_text into TITLE_INTRO components
    title_lib = lib_by_key.get("title_intro")
    if title_lib:
        for campaign in EmailCampaign.objects.all():
            h1 = getattr(campaign, "h1", "") or ""
            h1_small = getattr(campaign, "h1_small", "") or ""
            intro_text = getattr(campaign, "intro_text", "") or ""
            if not (h1 or h1_small or intro_text):
                continue
            try:
                title_comp = EmailCampaignComponent.objects.get(
                    campaign=campaign,
                    library_component=title_lib,
                )
                if not title_comp.title:
                    title_comp.title = h1
                if not title_comp.subtitle:
                    title_comp.subtitle = h1_small
                if not title_comp.body_html:
                    title_comp.body_html = intro_text
                title_comp.save(update_fields=["title", "subtitle", "body_html"])
            except EmailCampaignComponent.DoesNotExist:
                pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_emailcampaignproduct_discount_pct'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
