# Generated by Django 6.0.2 on 2026-06-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_data_migration_library_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='h1_small',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='product_template',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='component_key',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='mjml_markup',
        ),
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='library_component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_usages', to='emails.mjmlcomponent', verbose_name='Bibliotheks-Komponente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmailCampaignSalesChannel',
        ),
    ]
