# Generated by Django 6.0.2 on 2026-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_seed_mjml_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='title',
        ),
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-Value-Paare fuer Platzhalter im MJML-Template, z.B. {"titel": "Hallo"}', verbose_name='Variablen'),
        ),
    ]
