# Generated by Django 6.0.2 on 2026-06-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_replace_text_fields_with_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='campaign_product',
            field=models.ForeignKey(blank=True, help_text='Optionales Produkt fuer Produkt-Komponenten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='emails.emailcampaignproduct', verbose_name='Produkt'),
        ),
    ]
