# Generated by Django 6.0.2 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_emailcampaigncomponent_campaign_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjmlcomponent',
            name='detected_variables',
            field=models.JSONField(blank=True, default=list, verbose_name='Erkannte Variablen'),
        ),
        migrations.AddField(
            model_name='mjmlcomponent',
            name='variable_labels',
            field=models.JSONField(blank=True, default=dict, verbose_name='Variablen-Labels'),
        ),
    ]
