# Generated by Django 6.0.2 on 2026-06-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_mjmlcomponent_detected_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjmlcomponent',
            name='default_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-Value-Paare fuer Platzhalter. Werden in Kampagnen ueberschrieben.', verbose_name='Standard-Variablen'),
        ),
    ]
