# Generated by Django 6.0.2 on 2026-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_add_component_default_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='emailcampaignproduct',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Reihenfolge'),
        ),
    ]
