# Generated by Django 6.0.2 on 2026-06-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_alter_emailcampaigncomponent_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional fuer verschachtelte MJML-Strukturen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emails.emailcampaigncomponent', verbose_name='Übergeordnete Komponente'),
        ),
    ]
