# Generated by Django 6.0.2 on 2026-06-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_emailcampaigncomponent_parent'),
        ('products', '0030_delete_prices_without_sales_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alternativ zum absoluten Sonderpreis. Wird auf den Standardkanalpreis angewendet.', max_digits=5, null=True, verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='prices_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Preise synchronisiert am'),
        ),
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optionales Produkt fuer diese Kampagnen-Komponente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_campaign_components', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='special_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ueberschreibt den Sonderpreis des Produkts fuer diese Komponente.', max_digits=10, null=True, verbose_name='Sonderpreis'),
        ),
    ]
