# Generated by Django 6.0.2 on 2026-06-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0020_emailcampaigncomponent_discount_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='discount_pct',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='prices_synced_at',
        ),
        migrations.RemoveField(
            model_name='emailcampaigncomponent',
            name='special_price_override',
        ),
    ]
