# Generated by Django 6.0.2 on 2026-06-23 08:22

from django.db import migrations


IMAGE_URL_REPLACEMENTS = (
    (
        'src="https://assets.classei.de/img/{{img.name}}.{{img.type}}"',
        'src="{{ img.url }}"',
    ),
    (
        'src="https://assets.classei.de/img/{{ img.name }}.{{ img.type }}"',
        'src="{{ img.url }}"',
    ),
    (
        'src="https://assets.classei.de/img/{{product.first_image.name}}.{{product.first_image.type}}"',
        'src="{{ product.first_image.url }}"',
    ),
    (
        'src="https://assets.classei.de/img/{{ product.first_image.name }}.{{ product.first_image.type }}"',
        'src="{{ product.first_image.url }}"',
    ),
)


def update_product_component_image_urls(apps, schema_editor):
    MjmlComponent = apps.get_model("emails", "MjmlComponent")
    product_components = MjmlComponent.objects.filter(name__icontains="Produkt")

    for component in product_components:
        markup = component.mjml_markup or ""
        updated_markup = markup
        for old, new in IMAGE_URL_REPLACEMENTS:
            updated_markup = updated_markup.replace(old, new)
        if updated_markup != markup:
            component.mjml_markup = updated_markup
            component.save(update_fields=["mjml_markup"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0021_remove_emailcampaigncomponent_discount_pct_and_more'),
    ]

    operations = [
        migrations.RunPython(update_product_component_image_urls, noop_reverse),
    ]
