# Generated by Django 6.0.2 on 2026-06-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0022_update_product_component_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigncomponent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titel'),
        ),
    ]
