# Generated by Django 6.0.2 on 2026-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0023_emailcampaigncomponent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='send_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sendedatum'),
        ),
    ]
