# Generated by Django 6.0.2 on 2026-06-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_alter_customer_options_and_more'),
        ('emails', '0024_emailcampaign_send_at'),
        ('newsletter', '0003_newsletterrecipient_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='E-Mail')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Betreff')),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('sending', 'Wird gesendet'), ('sent', 'Gesendet'), ('failed', 'Fehler'), ('cancelled', 'Abgebrochen')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('rendered_mjml', models.TextField(blank=True, default='', verbose_name='Gerendertes MJML')),
                ('rendered_html', models.TextField(blank=True, default='', verbose_name='Gerendertes HTML')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehlermeldung')),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Eingereiht am')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='emails.emailcampaign', verbose_name='Kampagne')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_queue_entries', to='customer.customer', verbose_name='Kunde')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_queue_entries', to='newsletter.newsletterrecipient', verbose_name='Newsletter Empfaenger')),
            ],
            options={
                'verbose_name': 'E-Mail Warteschlangen-Eintrag',
                'verbose_name_plural': 'E-Mail Warteschlange',
                'ordering': ('-queued_at',),
                'indexes': [models.Index(fields=['status', 'queued_at'], name='email_queue_status_queued_idx')],
            },
        ),
    ]
