# Generated by Django 6.0.2 on 2026-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0025_emailcampaignqueueentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjmlcomponent',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Reihenfolge'),
        ),
    ]
