# Generated by Django 6.0.2 on 2026-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0026_alter_mjmlcomponent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjmlcomponent',
            name='rendering_mode',
            field=models.CharField(choices=[('jinja', 'Django/Jinja rendern'), ('shopware', 'Unverändert an Shopware weitergeben')], default='jinja', help_text='Django/Jinja rendert Standard-Variablen. Der Shopware-Modus gibt das Markup einschließlich Shopware-Platzhaltern unverändert weiter.', max_length=20, verbose_name='Rendering-Modus'),
        ),
        migrations.AlterField(
            model_name='mjmlcomponent',
            name='default_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-Value-Paare fuer Django/Jinja-Platzhalter. Werden in Kampagnen ueberschrieben und im Shopware-Modus nicht verwendet.', verbose_name='Standard-Variablen'),
        ),
    ]
