# Generated by Django 6.0.2 on 2026-08-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0027_mjmlcomponent_rendering_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'E-Mail Kategorie',
                'verbose_name_plural': 'E-Mail Kategorien',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='emailcampaignqueueentry',
            name='rendered_text',
            field=models.TextField(blank=True, default='', verbose_name='Gerenderter Text'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='emails.emailcampaigncategory', verbose_name='Kategorien'),
        ),
    ]
