# Generated by Django 6.0.2 on 2026-08-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0028_emailcampaigncategory_and_more'),
        ('newsletter', '0004_newsletterrecipient_selected_email_campaign'),
        ('products', '0046_productvariantfamily_description_ch_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ('-created_at',), 'verbose_name': 'E-Mail-Kampagne', 'verbose_name_plural': 'E-Mail-Kampagnen'},
        ),
        migrations.AlterModelOptions(
            name='emailcampaigncategory',
            options={'ordering': ('name',), 'verbose_name': 'E-Mail-Kategorie', 'verbose_name_plural': 'E-Mail-Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='emailcampaignqueueentry',
            options={'ordering': ('-queued_at',), 'verbose_name': 'E-Mail-Warteschlangen-Eintrag', 'verbose_name_plural': 'E-Mail-Warteschlange'},
        ),
        migrations.AlterModelOptions(
            name='mjmlcomponent',
            options={'ordering': ('order', 'name'), 'verbose_name': 'MJML-Komponente', 'verbose_name_plural': 'MJML-Komponenten'},
        ),
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='campaign_product',
            field=models.ForeignKey(blank=True, help_text='Optionales Produkt für Produkt-Komponenten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='emails.emailcampaignproduct', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional für verschachtelte MJML-Strukturen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emails.emailcampaigncomponent', verbose_name='Übergeordnete Komponente'),
        ),
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optionales Produkt für diese Kampagnen-Komponente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_campaign_components', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='emailcampaigncomponent',
            name='variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-Value-Paare für Platzhalter im MJML-Template, z. B. {"titel": "Hallo"}', verbose_name='Variablen'),
        ),
        migrations.AlterField(
            model_name='emailcampaignqueueentry',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_queue_entries', to='newsletter.newsletterrecipient', verbose_name='Newsletter-Empfänger'),
        ),
        migrations.AlterField(
            model_name='mjmlcomponent',
            name='default_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-Value-Paare für Django/Jinja-Platzhalter. Werden in Kampagnen überschrieben und im Shopware-Modus nicht verwendet.', verbose_name='Standard-Variablen'),
        ),
    ]
