# Generated by Django 6.0.2 on 2026-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0029_alter_emailcampaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='editor_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='layout_mode',
            field=models.CharField(choices=[('components', 'Komponenten (bisheriger Aufbau)'), ('simple', 'Einfacher Editor')], default='components', max_length=20),
        ),
    ]
