# Generated by Django 6.0.2 on 2026-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0030_emailcampaign_editor_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='layout_mode',
            field=models.CharField(choices=[('components', 'Komponenten (bisheriger Aufbau)'), ('simple', 'Einfacher Editor'), ('visual', 'Visueller MJML-Editor')], default='components', max_length=20),
        ),
    ]
