# Generated by Django 6.0.2 on 2026-09-30 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0031_alter_emailcampaign_layout_mode'),
        ('newsletter', '0005_add_newsletter_recipient_erp_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=False, help_text='Der spätere Versand-Worker darf diese Konfiguration nur aktiviert verwenden.', verbose_name='Für Newsletter-Versand aktiviert')),
                ('host', models.CharField(blank=True, default='', help_text='Zum Beispiel smtp.office365.com', max_length=255, verbose_name='SMTP-Server')),
                ('port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='SMTP-Port')),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Keine')], default='starttls', max_length=16, verbose_name='Verschlüsselung')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Benutzername')),
                ('password', models.CharField(blank=True, default='', max_length=500, verbose_name='Passwort')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Absendername')),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Absenderadresse')),
                ('reply_to_email', models.EmailField(blank=True, default='', help_text='Optional. Ohne Angabe wird die Absenderadresse verwendet.', max_length=254, verbose_name='Antwortadresse')),
                ('timeout', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout in Sekunden')),
            ],
            options={
                'verbose_name': 'SMTP-Einstellungen',
                'verbose_name_plural': 'SMTP-Einstellungen',
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='preview_recipient',
            field=models.ForeignKey(blank=True, help_text='Dieser Newsletter-Empfänger liefert die Platzhalterdaten für Vorschau und Export.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_campaigns', to='newsletter.newsletterrecipient', verbose_name='Vorschau-Empfänger'),
        ),
    ]
