# Generated by Django 6.0.2 on 2026-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0032_campaign_preview_recipient_and_smtp_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='layout_mode',
            field=models.CharField(choices=[('components', 'Komponenten (bisheriger Aufbau)'), ('simple', 'Einfacher Editor'), ('visual', 'Visueller MJML-Editor')], default='simple', max_length=20),
        ),
    ]
