# Generated by Django 6.0.2 on 2026-09-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0033_default_campaigns_to_simple_editor'),
        ('products', '0053_remove_maboxexportsettings_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignPriceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('price_snapshot', models.JSONField(blank=True, default=list, help_text='Interner Wiederherstellungszustand für entfernte oder geänderte Kampagnen-Produkte.', verbose_name='Preiszustand vor der Kampagne')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_price_states', to='emails.emailcampaign', verbose_name='Preisführende Kampagne')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_price_state', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Kampagnen-Preiszustand',
                'verbose_name_plural': 'Kampagnen-Preiszustände',
            },
        ),
    ]
