# Generated by Django 6.0.2 on 2026-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0034_emailcampaignpricestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Wird als Betreff der versendeten Newsletter-E-Mail verwendet.', max_length=255, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf (inaktiv)'), ('ready', 'Bereit (aktiv)'), ('exported', 'Exportiert (inaktiv)')], db_index=True, default='draft', help_text='Entwurf ist inaktiv. Bereit aktiviert die Kampagne für die automatische Versand-Queue. Exportiert kennzeichnet eine abgeschlossene oder extern verwendete Kampagne und ist ebenfalls inaktiv.', max_length=20, verbose_name='Status'),
        ),
    ]
