# Generated by Django 6.0.2 on 2026-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0035_emailcampaign_subject_alter_emailcampaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='shopware_price_activation_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='SW6-Preisaktivierung'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='shopware_prices_activated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='SW6-Preise aktiviert am'),
        ),
    ]
