# Generated by Django 6.0.2 on 2026-06-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('unique_packaging_id', models.CharField(help_text='Pflichtangabe nach PPWR Art. 11 – eindeutige Kennzeichnung der Verpackungseinheit.', max_length=255, verbose_name='Eindeutiges Identifikationsmerkmal')),
                ('canvas_width_mm', models.PositiveSmallIntegerField(default=100, verbose_name='Breite (mm)')),
                ('canvas_height_mm', models.PositiveSmallIntegerField(default=60, verbose_name='Höhe (mm)')),
                ('layout_data', models.JSONField(default=list, help_text='Blockpositionen und -größen in mm als JSON. Wird vom Editor verwaltet.', verbose_name='Layout')),
                ('pdf_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='PDF-Dateiname')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_labels', to='organization.companyprofile', verbose_name='Firmendaten')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_labels', to='qrcodes.qrcode', verbose_name='QR-Code')),
            ],
            options={
                'verbose_name': 'Verpackungsetikett',
                'verbose_name_plural': 'Verpackungsetiketten',
                'ordering': ('name',),
            },
        ),
    ]
