# Generated by Django 6.0.2 on 2026-06-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppwr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonformitaetsErklaerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('declaration_number', models.CharField(help_text='Anhang VIII, Kopf: Eindeutige Kennnummer der Erklärung.', max_length=100, verbose_name='Erklärungsnummer')),
                ('erzeuger_name_anschrift', models.TextField(help_text='Anhang VIII, Nr. 2: Name, Anschrift und ggf. Bevollmächtigter des Erzeugers.', verbose_name='Name und Anschrift des Erzeugers')),
                ('gegenstand_beschreibung', models.TextField(help_text='Anhang VIII, Nr. 4: Kennung der Verpackung zwecks Rückverfolgbarkeit.', verbose_name='Beschreibung der Verpackung')),
                ('harmonisierung', models.TextField(help_text='Anhang VIII, Nr. 5: Verweis auf die angewandten Rechtsakte der Union, z. B. PPWR (EU) 2025/...', verbose_name='Harmonisierung')),
                ('normen_spezifikationen', models.TextField(help_text='Anhang VIII, Nr. 6: Harmonisierte Normen oder gemeinsame Spezifikationen.', verbose_name='Normen / Spezifikationen')),
                ('notifizierte_stelle', models.TextField(blank=True, default='', help_text='Anhang VIII, Nr. 7: Name, Anschrift, Kennnummer der notifizierten Stelle (falls anwendbar).', verbose_name='Notifizierte Stelle')),
                ('zusaetzliche_angaben', models.TextField(blank=True, default='', help_text='Anhang VIII, Nr. 8: Optionale weitere Angaben.', verbose_name='Zusätzliche Angaben')),
                ('ausstellungsort', models.CharField(max_length=255, verbose_name='Ausstellungsort')),
                ('ausstellungsdatum', models.DateField(verbose_name='Ausstellungsdatum')),
                ('unterzeichner_name', models.CharField(max_length=255, verbose_name='Name des Unterzeichners')),
                ('unterzeichner_funktion', models.CharField(max_length=255, verbose_name='Funktion des Unterzeichners')),
                ('pdf_filename', models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='PDF-Dateiname')),
                ('pdf_generated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='PDF erstellt am')),
                ('packaging_label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='konformitaetserklaerung', to='ppwr.packaginglabel', verbose_name='Verpackungsetikett')),
            ],
            options={
                'verbose_name': 'EU-Konformitätserklärung',
                'verbose_name_plural': 'EU-Konformitätserklärungen',
                'ordering': ('-ausstellungsdatum',),
            },
        ),
    ]
