# Generated by Django 6.0.2 on 2026-06-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppwr', '0002_add_konformitaetserklaerung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KonformitaetsErklaerung',
        ),
    ]
