# Generated by Django 6.0.2 on 2026-06-11 14:08

import django.core.validators
import django.db.models.deletion
import issues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('color', models.CharField(blank=True, default='#64748b', max_length=20, verbose_name='Farbe')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Issue-Kategorie',
                'verbose_name_plural': 'Issue-Kategorien',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(help_text='Ein kurzer Satz reicht. Details, Link oder Screenshots koennen unten ergaenzt werden.', max_length=255, verbose_name='Kurzbeschreibung')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('waiting', 'Wartet'), ('resolved', 'Erledigt'), ('closed', 'Geschlossen')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend')], db_index=True, default='normal', max_length=20, verbose_name='Prioritaet')),
                ('description', models.TextField(blank=True, default='', help_text='Optional: Was ist passiert? Was wurde erwartet?', verbose_name='Beschreibung')),
                ('source_url', models.URLField(blank=True, default='', help_text='Optional: Seite, Admin-Link, Shopware-Link oder externe Referenz.', max_length=500, verbose_name='Link')),
                ('error_text', models.TextField(blank=True, default='', help_text='Optional: Fehlermeldung, Stacktrace oder kopierter Logauszug.', verbose_name='Fehlertext')),
                ('error_file', models.FileField(blank=True, help_text='Optional: Datei mit Fehlermeldung oder Logauszug.', upload_to=issues.models.issue_error_upload_to, validators=[django.core.validators.FileExtensionValidator(['txt', 'log', 'json', 'xml', 'html', 'csv'])], verbose_name='Fehlertext-Datei')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('reported_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Gemeldet von')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.issuecategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('attachment_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('error_file', 'Fehlerdatei'), ('other', 'Sonstiges')], default='screenshot', max_length=20, verbose_name='Art')),
                ('file', models.FileField(help_text='Screenshot, PDF oder Fehlerdatei.', upload_to=issues.models.issue_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'pdf', 'txt', 'log', 'json'])], verbose_name='Datei')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue-Anhang',
                'verbose_name_plural': 'Issue-Anhaenge',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
