# Generated by Django 6.0.2 on 2026-08-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedIssue',
            fields=[
            ],
            options={
                'verbose_name': 'Archiviertes Issue',
                'verbose_name_plural': 'Issue-Archiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('issues.issue',),
        ),
    ]
