# Generated by Django 6.0.2 on 2026-08-05 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_archivedissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_note',
            field=models.TextField(blank=True, default='', help_text='Bei Erledigt oder Geschlossen erforderlich: Was wurde gemacht und warum? Zeitpunkt und Bearbeiter werden automatisch festgehalten.', verbose_name='Lösungsdokumentation'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Abgeschlossen am'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL, verbose_name='Abgeschlossen von'),
        ),
        migrations.CreateModel(
            name='IssueAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Issue-Meldung')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_alert_state', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Issue-Meldestatus',
                'verbose_name_plural': 'Issue-Meldestatus',
            },
        ),
    ]
