# Generated by Django 6.0.2 on 2026-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_resolution_note_issue_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend')], db_index=True, default='normal', max_length=20, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Ein kurzer Satz reicht. Details, Link oder Screenshots können unten ergänzt werden.', max_length=255, verbose_name='Kurzbeschreibung'),
        ),
    ]
