# Generated by Django 6.0.2 on 2026-06-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0006_companyholiday_day_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Firmenname')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Rechtlicher Name')),
                ('tagline', models.CharField(blank=True, default='', max_length=255, verbose_name='Kurzbeschreibung')),
                ('logo', models.ImageField(blank=True, upload_to='organization/logos/', verbose_name='Logo')),
                ('logo_alt_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Logo Alternativtext')),
                ('street', models.CharField(blank=True, default='', max_length=255, verbose_name='Strasse und Hausnummer')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Ort')),
                ('region', models.CharField(blank=True, default='', max_length=120, verbose_name='Region/Kanton')),
                ('country', models.CharField(blank=True, default='', max_length=120, verbose_name='Land')),
                ('phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, default='', verbose_name='Webseite')),
                ('vat_id', models.CharField(blank=True, default='', max_length=80, verbose_name='USt-IdNr.')),
                ('tax_number', models.CharField(blank=True, default='', max_length=80, verbose_name='Steuernummer')),
                ('commercial_register', models.CharField(blank=True, default='', max_length=255, verbose_name='Handelsregister')),
                ('register_court', models.CharField(blank=True, default='', max_length=255, verbose_name='Registergericht')),
                ('managing_directors', models.TextField(blank=True, default='', verbose_name='Geschaeftsfuehrung')),
                ('bank_details', models.TextField(blank=True, default='', verbose_name='Bankverbindung')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Interne Notizen')),
            ],
            options={
                'verbose_name': 'Firmendaten',
                'verbose_name_plural': 'Firmendaten',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Rolle')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1000, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Ansprechpartner-Rolle',
                'verbose_name_plural': 'Ansprechpartner-Rollen',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('document_type', models.CharField(choices=[('terms', 'AGB'), ('imprint', 'Impressum'), ('privacy', 'Datenschutz'), ('other', 'Sonstiges')], max_length=30, verbose_name='Dokumenttyp')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='Version')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gueltig ab')),
                ('content', models.TextField(blank=True, default='', verbose_name='Inhalt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='organization.companyprofile', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Rechtstext',
                'verbose_name_plural': 'Rechtstexte',
                'ordering': ('document_type', '-valid_from', '-updated_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'document_type'), name='unique_active_legal_document_per_type')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Titel/Funktion')),
                ('public_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Oeffentliche E-Mail')),
                ('public_phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Oeffentliches Telefon')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primaerer Ansprechpartner')),
                ('is_public', models.BooleanField(default=True, verbose_name='Oeffentlich sichtbar')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1000, verbose_name='Sortierung')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Interne Notizen')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.companyprofile', verbose_name='Firma')),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_contacts', to='hr.employeeprofile', verbose_name='Mitarbeiterprofil')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='organization.organizationrole', verbose_name='Rolle')),
            ],
            options={
                'verbose_name': 'Ansprechpartner',
                'verbose_name_plural': 'Ansprechpartner',
                'ordering': ('sort_order', 'role__name', 'employee_profile__user__last_name'),
                'constraints': [models.UniqueConstraint(fields=('company', 'employee_profile', 'role'), name='unique_organization_contact_role'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company', 'role'), name='unique_primary_organization_contact_per_role')],
            },
        ),
    ]
