# Generated by Django 6.0.2 on 2026-09-29 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='Zum Beispiel smtp.office365.com', max_length=255, verbose_name='SMTP-Server'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='SMTP-Passwort'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='SMTP-Port'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_security',
            field=models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Keine')], default='starttls', max_length=16, verbose_name='SMTP-Verschlüsselung'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_sender_email',
            field=models.EmailField(blank=True, default='', help_text='Leer lassen, um die E-Mail-Adresse des Ansprechpartners zu verwenden.', max_length=254, verbose_name='SMTP-Absenderadresse'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_timeout',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='SMTP-Timeout in Sekunden'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP-Benutzername'),
        ),
    ]
