# Generated by Django 6.0.2 on 2026-07-13 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung')),
                ('table_names', models.JSONField(blank=True, default=list, verbose_name='Gesicherte Tabellen')),
                ('status', models.CharField(choices=[('queued', 'Eingereiht'), ('running', 'Laeuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], db_index=True, default='queued', max_length=16, verbose_name='Backup-Status')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Dateiname')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Dateigroesse (Bytes)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Backup-Fehler')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Backup gestartet am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Backup abgeschlossen am')),
                ('restore_table_names', models.JSONField(blank=True, default=list, verbose_name='Wiederhergestellte Tabellen')),
                ('restore_status', models.CharField(choices=[('not_requested', 'Nicht angefordert'), ('queued', 'Eingereiht'), ('running', 'Laeuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], db_index=True, default='not_requested', max_length=16, verbose_name='Wiederherstellungs-Status')),
                ('restore_error_message', models.TextField(blank=True, default='', verbose_name='Wiederherstellungs-Fehler')),
                ('restore_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Wiederherstellung gestartet am')),
                ('restore_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Wiederherstellung abgeschlossen am')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_database_backups', to=settings.AUTH_USER_MODEL, verbose_name='Backup angefordert von')),
                ('restore_requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_database_restores', to=settings.AUTH_USER_MODEL, verbose_name='Wiederherstellung angefordert von')),
            ],
            options={
                'verbose_name': 'Datenbank-Backup',
                'verbose_name_plural': 'Datenbank-Backups',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
