# Generated by Django 6.0.2 on 2026-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.CharField(db_index=True, max_length=120, verbose_name='Task')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entity', models.CharField(blank=True, default='', max_length=120)),
                ('target', models.CharField(blank=True, default='', max_length=40)),
                ('step', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('error', 'Fehler'), ('skipped', 'Übersprungen')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync-Ereignis',
                'verbose_name_plural': 'Sync-Ereignisse',
                'ordering': ('-created_at',),
            },
        ),
    ]
