# Generated by Django 6.0.2 on 2026-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_synceventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackup',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Dateigröße (Bytes)'),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='restore_status',
            field=models.CharField(choices=[('not_requested', 'Nicht angefordert'), ('queued', 'Eingereiht'), ('running', 'Läuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], db_index=True, default='not_requested', max_length=16, verbose_name='Wiederherstellungs-Status'),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='status',
            field=models.CharField(choices=[('queued', 'Eingereiht'), ('running', 'Läuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], db_index=True, default='queued', max_length=16, verbose_name='Backup-Status'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='entity',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Entität'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Meldung'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Nutzdaten'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Lauf-ID'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='status',
            field=models.CharField(choices=[('error', 'Fehler'), ('skipped', 'Übersprungen')], max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='step',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Schritt'),
        ),
        migrations.AlterField(
            model_name='synceventlog',
            name='target',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Zielsystem'),
        ),
    ]
