# Generated by Django 6.0.2 on 2026-02-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_nr', models.CharField(max_length=64, unique=True)),
                ('erp_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('api_id', models.CharField(blank=True, default='', max_length=255)),
                ('vat_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_gross', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('erp_nr',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_combined_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('api_id', models.CharField(blank=True, default='', max_length=255)),
                ('erp_nr', models.IntegerField(blank=True, null=True)),
                ('erp_ans_id', models.IntegerField(blank=True, null=True)),
                ('erp_ans_nr', models.IntegerField(blank=True, null=True)),
                ('erp_asp_id', models.IntegerField(blank=True, null=True)),
                ('erp_asp_nr', models.IntegerField(blank=True, null=True)),
                ('name1', models.CharField(blank=True, default='', max_length=255)),
                ('name2', models.CharField(blank=True, default='', max_length=255)),
                ('name3', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=8)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('is_shipping', models.BooleanField(default=False)),
                ('is_invoice', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer')),
            ],
            options={
                'ordering': ('customer', 'erp_ans_id', 'erp_asp_id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('erp_ans_id__isnull', False)), fields=('customer', 'erp_ans_id'), name='unique_customer_anschrift')],
            },
        ),
    ]
