# Generated by Django 6.0.2 on 2026-02-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('customer', 'erp_ans_id', 'erp_asp_id'), 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adressen'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('erp_nr',), 'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AlterField(
            model_name='address',
            name='api_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shopware Adress-ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Laendercode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='address',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Abteilung'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_ans_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anschrift-ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_ans_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anschrift-Nummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_asp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ansprechpartner-ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_asp_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ansprechpartner-Nummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_combined_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ERP Kombi-ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='erp_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='ERP-Nummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_invoice',
            field=models.BooleanField(default=False, verbose_name='Rechnungsanschrift'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_shipping',
            field=models.BooleanField(default=False, verbose_name='Lieferanschrift'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='api_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shopware Kunden-ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='erp_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ERP-ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='erp_nr',
            field=models.CharField(max_length=64, unique=True, verbose_name='ERP-Nummer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_gross',
            field=models.BooleanField(default=True, verbose_name='Bruttopreise'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='USt-IdNr'),
        ),
    ]
