# Generated by Django 6.0.2 on 2026-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_customer_anschrift',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('erp_ans_id__isnull', False), ('erp_asp_id__isnull', True)), fields=('customer', 'erp_ans_id'), name='unique_customer_anschrift_without_contact'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('erp_ans_id__isnull', False), ('erp_asp_id__isnull', False)), fields=('customer', 'erp_ans_id', 'erp_asp_id'), name='unique_customer_anschrift_contact'),
        ),
    ]
