# Generated by Django 6.0.2 on 2026-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_address_unique_customer_anschrift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shopware_customer_group',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shopware Kundengruppe'),
        ),
    ]
