# Generated by Django 6.0.2 on 2026-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_shopware_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Ländercode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Straße'),
        ),
    ]
