# Generated by Django 6.0.2 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_address_country_code_alter_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Firma (Shopware)'),
        ),
    ]
