# Generated by Django 6.0.2 on 2026-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Firma'),
        ),
    ]
