# Generated by Django 6.0.2 on 2026-06-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0016_mjmlcomponent_detected_variables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBuilderCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('internal_title', models.CharField(max_length=255, verbose_name='Interner Titel')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Bereit'), ('exported', 'Exportiert')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Email Kampagne (v2)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('tag', models.CharField(max_length=50)),
                ('attributes', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.mjmlcomponent')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emails_v2.emailblock')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='emails_v2.emailbuildercampaign')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
