# Generated by Django 6.0.2 on 2026-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbuildercampaign',
            name='global_css',
            field=models.TextField(blank=True, default='', verbose_name='Globale CSS-Regeln'),
        ),
    ]
