# Generated by Django 6.0.2 on 2026-06-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_v2', '0002_global_css'),
        ('products', '0030_delete_prices_without_sales_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBuilderCampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('special_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonderpreis')),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rabatt (%)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='emails_v2.emailbuildercampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_builder_campaign_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Email Builder Produkt',
                'verbose_name_plural': 'Email Builder Produkte',
                'ordering': ('order', 'id'),
                'unique_together': {('campaign', 'product')},
            },
        ),
        migrations.AddField(
            model_name='emailblock',
            name='campaign_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='emails_v2.emailbuildercampaignproduct'),
        ),
    ]
