# Generated by Django 6.0.2 on 2026-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('shopware_id', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='Shopware ID')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='E-Mail')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titel')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nachname')),
                ('zip_code', models.CharField(blank=True, default='', max_length=64, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='Ort')),
                ('street', models.CharField(blank=True, default='', max_length=255, verbose_name='Strasse')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Status')),
                ('hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Hash')),
                ('sales_channel_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Sales-Channel ID')),
                ('language_id', models.CharField(blank=True, default='', max_length=36, verbose_name='Sprach-ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bestaetigt am')),
                ('remote_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Shopware angelegt am')),
                ('remote_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Shopware aktualisiert am')),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Zuletzt synchronisiert am')),
                ('is_present_in_shopware', models.BooleanField(db_index=True, default=True, verbose_name='In Shopware vorhanden')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Shopware Rohdaten')),
            ],
            options={
                'verbose_name': 'Newsletter Empfaenger',
                'verbose_name_plural': 'Newsletter Empfaenger',
                'ordering': ('email', 'last_name', 'first_name'),
                'indexes': [models.Index(fields=['status', 'email'], name='newsletter_status_email_idx')],
            },
        ),
    ]
