# Generated by Django 6.0.2 on 2026-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='salutation_display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Anrede'),
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='salutation_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Anrede ID'),
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='salutation_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Anrede Schluessel'),
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='salutation_letter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Briefanrede'),
        ),
        migrations.AlterField(
            model_name='newsletterrecipient',
            name='status',
            field=models.CharField(blank=True, choices=[('notSet', 'Nicht bestaetigt'), ('optIn', 'Bestaetigt'), ('optOut', 'Abgemeldet'), ('direct', 'Direkt aktiv')], db_index=True, default='', max_length=64, verbose_name='Status'),
        ),
    ]
