# Generated by Django 6.0.2 on 2026-06-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_alter_customer_options_and_more'),
        ('newsletter', '0002_newsletterrecipient_salutation_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_recipients', to='customer.customer', verbose_name='Django Kunde'),
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='customer_shopware_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Shopware Kunden-ID'),
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ist Kunde'),
        ),
    ]
