# Generated by Django 6.0.2 on 2026-06-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0025_emailcampaignqueueentry'),
        ('newsletter', '0003_newsletterrecipient_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='selected_email_campaign',
            field=models.ForeignKey(blank=True, help_text='Diese Kampagne wird fuer die Queue-Action dieses Empfaengers gerendert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_newsletter_recipients', to='emails.emailcampaign', verbose_name='Ausgewaehlte E-Mail Kampagne'),
        ),
    ]
