# Generated by Django 6.0.2 on 2026-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletterrecipient_selected_email_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='erp_nr',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Aus dem AdrNr-Custom-Field des Shopware Newsletter-Empfaengers.', max_length=64, verbose_name='ERP-/Adressnummer'),
        ),
    ]
