# Generated by Django 6.0.2 on 2026-05-05 08:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Abteilung')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Kuerzel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Arbeitszeitmodell',
                'verbose_name_plural': 'Arbeitszeitmodelle',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('employee_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Personalnummer')),
                ('short_code', models.CharField(max_length=10, verbose_name='Kuerzel')),
                ('color', models.CharField(default='#3788d8', max_length=20, verbose_name='Kalenderfarbe')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Aktiver Mitarbeiter')),
                ('vacation_days_per_year', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Urlaubstage pro Jahr')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department', verbose_name='Abteilung')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ('user__last_name', 'user__first_name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('leave_type', models.CharField(choices=[('vacation', 'Urlaub'), ('special_leave', 'Sonderurlaub'), ('overtime_reduction', 'Ueberstundenabbau')], default='vacation', max_length=30, verbose_name='Art')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('half_day_start', models.BooleanField(default=False, verbose_name='Halber Tag am Starttag')),
                ('half_day_end', models.BooleanField(default=False, verbose_name='Halber Tag am Endtag')),
                ('status', models.CharField(choices=[('requested', 'Beantragt'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='requested', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Urlaubsantrag',
                'verbose_name_plural': 'Urlaubsantraege',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Attest vorhanden')),
                ('note', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Krankheit',
                'verbose_name_plural': 'Krankheitstage',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TimeAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('date', models.DateField(verbose_name='Datum')),
                ('entry_type', models.CharField(choices=[('extra_work', 'Mehrarbeit / Ueberstunden'), ('minus_time', 'Minusstunden'), ('correction', 'Manuelle Korrektur'), ('overtime_reduction', 'Ueberstundenabbau')], max_length=30, verbose_name='Art')),
                ('minutes', models.IntegerField(help_text='Plus fuer Ueberstunden, Minus fuer Minusstunden.', verbose_name='Minuten')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Begruendung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('requested', 'Beantragt'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='requested', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_account_entries', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_account_entries', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Zeitkonto-Buchung',
                'verbose_name_plural': 'Zeitkonto-Buchungen',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('valid_from', models.DateField(verbose_name='Gueltig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gueltig bis')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule_assignments', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.workschedule', verbose_name='Arbeitszeitmodell')),
            ],
            options={
                'verbose_name': 'Mitarbeiter-Arbeitszeitmodell',
                'verbose_name_plural': 'Mitarbeiter-Arbeitszeitmodelle',
                'ordering': ('employee', '-valid_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MonthlyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('month', models.PositiveIntegerField(verbose_name='Monat')),
                ('target_minutes', models.IntegerField(default=0, verbose_name='Soll-Minuten')),
                ('vacation_minutes', models.IntegerField(default=0, verbose_name='Urlaubs-Minuten')),
                ('sick_minutes', models.IntegerField(default=0, verbose_name='Krankheits-Minuten')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='Ueberstunden')),
                ('minus_minutes', models.IntegerField(default=0, verbose_name='Minusstunden')),
                ('balance_minutes', models.IntegerField(default=0, verbose_name='Saldo')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Berechnet am')),
                ('locked', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Monatsuebersicht Arbeitszeit',
                'verbose_name_plural': 'Monatsuebersichten Arbeitszeit',
                'ordering': ('-year', '-month', 'employee'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_monthly_work_summary'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_summary_month_range')],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('weekday', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Beginn')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Ende')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Pause in Minuten')),
                ('target_minutes', models.PositiveIntegerField(default=0, verbose_name='Soll-Arbeitszeit in Minuten')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Arbeitstag')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hr.workschedule', verbose_name='Arbeitszeitmodell')),
            ],
            options={
                'verbose_name': 'Arbeitszeit pro Wochentag',
                'verbose_name_plural': 'Arbeitszeiten pro Wochentag',
                'ordering': ('schedule', 'weekday'),
                'constraints': [models.UniqueConstraint(fields=('schedule', 'weekday'), name='unique_work_schedule_weekday'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='work_schedule_weekday_range')],
            },
        ),
    ]
