# Generated by Django 6.0.2 on 2026-05-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('counts_as_vacation', models.BooleanField(default=False, verbose_name='Zaehlt als Urlaub')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('note', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
            ],
            options={
                'verbose_name': 'Betriebsurlaub',
                'verbose_name_plural': 'Betriebsurlaube',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('region_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Region')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standardkalender')),
            ],
            options={
                'verbose_name': 'Feiertagskalender',
                'verbose_name_plural': 'Feiertagskalender',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='holiday_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.holidaycalendar', verbose_name='Feiertagskalender'),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Feiertag')),
                ('date', models.DateField(verbose_name='Datum')),
                ('is_half_day', models.BooleanField(default=False, verbose_name='Halber Tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='hr.holidaycalendar', verbose_name='Feiertagskalender')),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
                'ordering': ('date', 'name'),
                'constraints': [models.UniqueConstraint(fields=('calendar', 'date'), name='unique_public_holiday_per_calendar')],
            },
        ),
    ]
