# Generated by Django 6.0.2 on 2026-05-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_companyholiday_holidaycalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, verbose_name='Ferien')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('source_subdivisions', models.CharField(blank=True, default='', max_length=255, verbose_name='Regionen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('note', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_holidays', to='hr.holidaycalendar', verbose_name='Feiertagskalender')),
            ],
            options={
                'verbose_name': 'Ferientermin',
                'verbose_name_plural': 'Ferientermine',
                'ordering': ('start_date', 'end_date', 'name'),
                'constraints': [models.UniqueConstraint(fields=('calendar', 'name', 'start_date', 'end_date'), name='unique_school_holiday_per_calendar')],
            },
        ),
    ]
