# Generated by Django 6.0.2 on 2026-05-06 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_schoolholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='calculated_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Berechnete Tage'),
        ),
    ]
