# Generated by Django 6.0.2 on 2026-05-06 12:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_leaverequest_calculated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholiday',
            name='is_bridge_day',
            field=models.BooleanField(default=False, verbose_name='Brueckentag'),
        ),
        migrations.CreateModel(
            name='VacationEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('base_days', models.DecimalField(decimal_places=2, help_text='Jahresurlaubsanspruch laut Vertrag.', max_digits=5, verbose_name='Basistage')),
                ('carryover_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Resturlaub Vorjahr')),
                ('carryover_expires_on', models.DateField(blank=True, help_text='Standard: 31.03. des Jahres. Danach wird der Resturlaub nicht mehr angerechnet.', null=True, verbose_name='Resturlaub verfaellt am')),
                ('note', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_entitlements', to='hr.employeeprofile', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Jahresurlaubs-Konto',
                'verbose_name_plural': 'Jahresurlaubs-Konten',
                'ordering': ('-year', 'employee'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'year'), name='unique_vacation_entitlement')],
            },
        ),
    ]
