# Generated by Django 6.0.2 on 2026-05-06 13:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_bridge_day_and_vacation_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholiday',
            name='day_fraction',
            field=models.DecimalField(choices=[(Decimal('1.00'), 'Ganzer Tag'), (Decimal('0.50'), 'Halber Tag')], decimal_places=2, default=Decimal('1.00'), help_text='1.00 = ganzer Tag, 0.50 = halber Tag.', max_digits=3, verbose_name='Tagesanteil'),
        ),
    ]
