# Generated by Django 6.0.2 on 2026-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_companyholiday_day_fraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ('-start_date', '-id'), 'verbose_name': 'Urlaubsantrag', 'verbose_name_plural': 'Urlaubsanträge'},
        ),
        migrations.AlterModelOptions(
            name='monthlyworksummary',
            options={'ordering': ('-year', '-month', 'employee'), 'verbose_name': 'Monatsübersicht Arbeitszeit', 'verbose_name_plural': 'Monatsübersichten Arbeitszeit'},
        ),
        migrations.AlterField(
            model_name='companyholiday',
            name='counts_as_vacation',
            field=models.BooleanField(default=False, verbose_name='Zählt als Urlaub'),
        ),
        migrations.AlterField(
            model_name='companyholiday',
            name='is_bridge_day',
            field=models.BooleanField(default=False, verbose_name='Brückentag'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='short_code',
            field=models.CharField(max_length=10, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='employeeworkschedule',
            name='valid_from',
            field=models.DateField(verbose_name='Gültig ab'),
        ),
        migrations.AlterField(
            model_name='employeeworkschedule',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Urlaub'), ('special_leave', 'Sonderurlaub'), ('overtime_reduction', 'Überstundenabbau')], default='vacation', max_length=30, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='monthlyworksummary',
            name='overtime_minutes',
            field=models.IntegerField(default=0, verbose_name='Überstunden'),
        ),
        migrations.AlterField(
            model_name='timeaccountentry',
            name='entry_type',
            field=models.CharField(choices=[('extra_work', 'Mehrarbeit / Überstunden'), ('minus_time', 'Minusstunden'), ('correction', 'Manuelle Korrektur'), ('overtime_reduction', 'Überstundenabbau')], max_length=30, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='timeaccountentry',
            name='minutes',
            field=models.IntegerField(help_text='Plus für Überstunden, Minus für Minusstunden.', verbose_name='Minuten'),
        ),
        migrations.AlterField(
            model_name='timeaccountentry',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Begründung'),
        ),
        migrations.AlterField(
            model_name='vacationentitlement',
            name='carryover_expires_on',
            field=models.DateField(blank=True, help_text='Standard: 31.03. des Jahres. Danach wird der Resturlaub nicht mehr angerechnet.', null=True, verbose_name='Resturlaub verfällt am'),
        ),
    ]
