# Generated by Django 6.0.2 on 2026-09-23 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_leaverequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Anschrift')),
                ('travel_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum der Reise')),
                ('travel_start', models.DateTimeField(verbose_name='Reisebeginn')),
                ('travel_end', models.DateTimeField(verbose_name='Reiseende')),
                ('purpose', models.TextField(verbose_name='Anlass')),
                ('vehicle', models.CharField(max_length=120, verbose_name='Fahrzeug')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Kennzeichen')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Kilometer der einfachen Fahrt.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gefahrene km (einfache Fahrt)')),
                ('rate_per_km', models.DecimalField(decimal_places=3, help_text='Fahrtkostenpauschale in Euro pro Kilometer.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Fahrtkostenpauschale (EUR/km)')),
                ('round_trip', models.BooleanField(default=False, verbose_name='Hin- und Rückfahrt')),
                ('settlement_place', models.CharField(max_length=120, verbose_name='Ort der Abrechnung')),
                ('settlement_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum der Abrechnung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_expense_claims', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Reisekostenabrechnung',
                'verbose_name_plural': 'Reisekostenabrechnungen',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
