# Generated by Django 6.0.2 on 2026-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_travelexpenseclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelexpenseclaim',
            name='address',
        ),
        migrations.AlterField(
            model_name='travelexpenseclaim',
            name='travel_end',
            field=models.DateField(verbose_name='Reiseende'),
        ),
        migrations.AlterField(
            model_name='travelexpenseclaim',
            name='travel_start',
            field=models.DateField(verbose_name='Reisebeginn'),
        ),
    ]
