# Generated by Django 6.0.2 on 2026-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_remove_travelexpenseclaim_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpenseclaim',
            name='paid_out',
            field=models.BooleanField(default=False, verbose_name='Auszahlung erfolgt'),
        ),
    ]
