# Generated by Django 6.0.2 on 2026-09-23 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_travelexpenseclaim_paid_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelexpenseclaim',
            name='paid_out',
        ),
        migrations.AlterField(
            model_name='travelexpenseclaim',
            name='travel_end',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Reiseende'),
        ),
        migrations.AlterField(
            model_name='travelexpenseclaim',
            name='travel_start',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Reisebeginn'),
        ),
    ]
