# Generated by Django 6.0.2 on 2026-04-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0022_priceincreaseitem_last_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappeiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('artikelnr', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL')),
                ('vpe_menge', models.PositiveIntegerField(blank=True, null=True, verbose_name='VPE Menge')),
                ('vpe_einheit', models.CharField(blank=True, default='', max_length=64, verbose_name='VPE Einheit')),
                ('hat_staffel', models.BooleanField(default=False, verbose_name='Hat Staffelpreise')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gescrapt')),
            ],
            options={
                'verbose_name': 'Mappei Produkt',
                'verbose_name_plural': 'Mappei Produkte',
                'ordering': ('artikelnr',),
            },
        ),
        migrations.CreateModel(
            name='MappeiPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('scraped_at', models.DateTimeField(verbose_name='Gescrapt am')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (netto)')),
                ('staffelpreismenge_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Staffelmenge min (Stück)')),
                ('staffelpreismenge_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Staffelmenge max (Stück)')),
                ('staffelpreis_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Staffelpreis min')),
                ('staffelpreis_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Staffelpreis max')),
                ('partial_success', models.BooleanField(default=False, help_text='Staffelmengen konnten nicht berechnet werden (VPE fehlte).', verbose_name='Teilweise erfolgreich')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='mappei.mappeiproduct', verbose_name='Mappei Produkt')),
            ],
            options={
                'verbose_name': 'Mappei Preissnapshot',
                'verbose_name_plural': 'Mappei Preissnapshots',
                'ordering': ('-scraped_at',),
            },
        ),
        migrations.CreateModel(
            name='MappeiProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('factor', models.DecimalField(blank=True, decimal_places=4, help_text='Umrechnungsfaktor Mappei-VPE → interne Einheit. Leer lassen wenn 1:1.', max_digits=10, null=True, verbose_name='Faktor')),
                ('mappei_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='mappei.mappeiproduct', verbose_name='Mappei Produkt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappei_mappings', to='products.product', verbose_name='Internes Produkt')),
            ],
            options={
                'verbose_name': 'Mappei Produkt-Mapping',
                'verbose_name_plural': 'Mappei Produkt-Mappings',
                'ordering': ('mappei_product__artikelnr',),
            },
        ),
    ]
