# Generated by Django 6.0.2 on 2026-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappeiproduct',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Bild-URL'),
        ),
    ]
