# Generated by Django 6.0.2 on 2026-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappei', '0002_mappeiproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappeiproduct',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
    ]
