# Generated by Django 6.0.2 on 2026-04-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappei', '0003_mappeiproduct_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappeiproductmapping',
            name='factor',
        ),
    ]
