# Generated by Django 6.0.2 on 2026-04-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappei', '0004_remove_mappeiproductmapping_factor'),
        ('products', '0024_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappeiproduct',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='mappei_products', through='mappei.MappeiProductMapping', to='products.product', verbose_name='Classei Produkte'),
        ),
        migrations.AlterField(
            model_name='mappeiproductmapping',
            name='mappei_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='mappei.mappeiproduct', verbose_name='Mappei Produkt'),
        ),
        migrations.AddConstraint(
            model_name='mappeiproductmapping',
            constraint=models.UniqueConstraint(fields=('mappei_product', 'product'), name='unique_mappei_classei_product_mapping'),
        ),
    ]
