# Generated by Django 6.0.2 on 2026-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopwareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sales_channel_id', models.CharField(blank=True, max_length=255)),
                ('tax_high_id', models.CharField(blank=True, max_length=255)),
                ('tax_low_id', models.CharField(blank=True, max_length=255)),
                ('currency_id', models.CharField(blank=True, max_length=255)),
                ('rule_id_price', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shopware Settings',
                'verbose_name_plural': 'Shopware Settings',
            },
        ),
    ]
