# Generated by Django 6.0.2 on 2026-02-16 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0002_sales_channel_pricing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopwaresettings',
            options={'verbose_name': 'Shopware Konfiguration', 'verbose_name_plural': 'Shopware Konfigurationen'},
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='currency_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Waehrungs-ID'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Standardkanal'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='price_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10, verbose_name='Preisfaktor'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='rule_id_price',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preisregel-ID'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='sales_channel_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verkaufskanal-ID'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='tax_high_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Steuer-ID hoch'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='tax_low_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Steuer-ID niedrig'),
        ),
        migrations.AlterField(
            model_name='shopwaresettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
    ]
