# Generated by Django 6.0.2 on 2026-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0003_alter_shopwaresettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopwareConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('api_url', models.CharField(help_text='z.B. https://mein-shop.de/api', max_length=500, verbose_name='API URL')),
                ('client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, default='', max_length=500, verbose_name='Client Secret')),
                ('grant_type', models.CharField(choices=[('resource_owner', 'Resource Owner (Benutzername + Passwort)'), ('client_credentials', 'Client Credentials (ID + Secret)')], default='resource_owner', max_length=32, verbose_name='Grant Type')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Benutzername')),
                ('password', models.CharField(blank=True, default='', max_length=500, verbose_name='Passwort')),
            ],
            options={
                'verbose_name': 'Shopware Verbindung',
                'verbose_name_plural': 'Shopware Verbindung',
            },
        ),
    ]
