# Generated by Django 6.0.2 on 2026-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0004_shopwareconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopware5Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=False, help_text='Wenn aktiv, schreibt der Shopware-6-Produktsync Bestand, Preise und Aktiv-Status auch nach Shopware 5.', verbose_name='Shopware 5 Sync aktiv')),
                ('api_url', models.CharField(blank=True, default='', help_text='Optional. Falls leer, wird SHOPWARE5_API_URL aus der Umgebung verwendet.', max_length=500, verbose_name='API URL')),
                ('username', models.CharField(blank=True, default='', help_text='Optional. Falls leer, wird SHOPWARE5_API_USER aus der Umgebung verwendet.', max_length=255, verbose_name='API Benutzer')),
                ('api_token', models.CharField(blank=True, default='', help_text='Optional. Falls leer, wird SHOPWARE5_API_TOKEN aus der Umgebung verwendet.', max_length=500, verbose_name='API Token')),
                ('fail_on_error', models.BooleanField(default=False, help_text='Standard: Fehler werden protokolliert, aber der Shopware-6-Sync bleibt erfolgreich.', verbose_name='Sync bei Shopware-5-Fehler abbrechen')),
            ],
            options={
                'verbose_name': 'Shopware 5 Sync',
                'verbose_name_plural': 'Shopware 5 Sync',
            },
        ),
    ]
