# Generated by Django 6.0.2 on 2026-07-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0005_shopware5settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopware5settings',
            name='fail_on_error',
        ),
        migrations.RemoveField(
            model_name='shopware5settings',
            name='is_active',
        ),
    ]
