# Generated by Django 6.0.2 on 2026-08-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0006_remove_shopware5settings_fail_on_error_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopware5Settings',
        ),
    ]
