# Generated by Django 6.0.2 on 2026-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('document_type', models.CharField(choices=[('price_list', 'Preisliste'), ('order_form', 'Bestellschein'), ('terms', 'AGB'), ('privacy', 'Datenschutzerklaerung'), ('imprint', 'Impressum'), ('other', 'Sonstiges')], db_index=True, default='other', max_length=40, verbose_name='Dokumenttyp')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='HTML')),
                ('css_content', models.TextField(blank=True, default='', verbose_name='CSS')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('pdf_filename', models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='PDF-Dateiname')),
                ('pdf_generated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='PDF erzeugt am')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ('document_type', 'title'),
            },
        ),
    ]
