# Generated by Django 6.0.2 on 2026-06-08 11:40

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template_file',
            field=models.FileField(blank=True, help_text='Primaere Vorlage. Eine neue Datei wird ohne Container-Neustart beim Rendern geladen.', upload_to=documents.models.document_template_upload_to, validators=[django.core.validators.FileExtensionValidator(['html', 'htm'])], verbose_name='HTML-Template-Datei'),
        ),
    ]
