# Generated by Django 6.0.2 on 2026-06-09 06:07

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_pdf',
            field=models.FileField(blank=True, help_text='Wird dem generierten PDF vorangestellt.', upload_to=documents.models.document_cover_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Cover-PDF'),
        ),
        migrations.AddField(
            model_name='document',
            name='end_pdf',
            field=models.FileField(blank=True, help_text='Wird dem generierten PDF angehaengt.', upload_to=documents.models.document_end_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='End-PDF'),
        ),
        migrations.AddField(
            model_name='document',
            name='use_jinja2',
            field=models.BooleanField(default=True, help_text="Jinja2 erlaubt DB-Zugriff im Template, z. B. Product.objects.get(erp_nr='123').", verbose_name='Jinja2-Engine'),
        ),
    ]
