# Generated by Django 6.0.2 on 2026-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_shopware_media_id'),
        ('products', '0045_add_shopware5_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='price_list_duplicate_categories',
            field=models.ManyToManyField(blank=True, help_text='Artikel aus diesen Kategorien und ihren Unterkategorien duerfen in einer Preisliste zusaetzlich zu ihrer regulaeren Kategorie erscheinen.', limit_choices_to={'is_active': True}, related_name='price_list_duplicate_documents', to='products.category', verbose_name='Kategorien mit Doppelauflistung'),
        ),
    ]
