# Generated by Django 6.0.2 on 2026-08-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_price_list_duplicate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopwareCmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('shopware_id', models.CharField(max_length=64, unique=True, verbose_name='Shopware-ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('page_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Seitentyp')),
                ('is_locked', models.BooleanField(default=False, verbose_name='In Shopware gesperrt')),
                ('layout_description', models.TextField(blank=True, default='', verbose_name='Layoutbeschreibung')),
                ('remote_payload', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Shopware-Rohdaten')),
                ('last_fetched_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt abgerufen')),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt hochgeladen')),
            ],
            options={
                'verbose_name': 'Shopseite',
                'verbose_name_plural': 'Shopseiten',
                'ordering': ('title', 'shopware_id'),
            },
        ),
        migrations.CreateModel(
            name='ShopwareCmsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('shopware_id', models.CharField(max_length=64, unique=True, verbose_name='Shopware Slot-ID')),
                ('slot_type', models.CharField(max_length=100, verbose_name='Elementtyp')),
                ('slot_label', models.CharField(max_length=255, verbose_name='Position')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='HTML')),
                ('remote_html_content', models.TextField(blank=True, default='', editable=False, verbose_name='Zuletzt abgerufener HTML-Inhalt')),
                ('slot_config', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Slot-Konfiguration')),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt hochgeladen')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_slots', to='documents.shopwarecmspage', verbose_name='Shopseite')),
            ],
            options={
                'verbose_name': 'Shopseiten-Inhalt',
                'verbose_name_plural': 'Shopseiten-Inhalte',
                'ordering': ('page', 'slot_label', 'shopware_id'),
            },
        ),
    ]
