# Generated by Django 6.0.2 on 2026-08-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_shopware_cms_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung')),
                ('template_source', models.TextField(verbose_name='HTML-Vorlage')),
                ('css_content', models.TextField(blank=True, default='', verbose_name='CSS')),
                ('use_jinja2', models.BooleanField(default=True, verbose_name='Jinja2-Engine')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Aktiv')),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Aktiviert am')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Dokumentversion',
                'verbose_name_plural': 'Dokumentversionen',
                'ordering': ('document', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='active_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_documents', to='documents.documentversion', verbose_name='Aktive Version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='documents_unique_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='documents_one_active_version_per_document'),
        ),
    ]
