# Generated by Django 6.0.2 on 2026-08-05 07:22

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopwarecmsslot',
            name='page',
        ),
        migrations.AddField(
            model_name='document',
            name='source_docx',
            field=models.FileField(blank=True, help_text='Wird rechts als schreibgeschuetzte PDF-Vorschau angezeigt.', upload_to=documents.models.document_source_docx_upload_to, validators=[django.core.validators.FileExtensionValidator(['docx'])], verbose_name='DOCX-Quelldatei'),
        ),
        migrations.DeleteModel(
            name='ShopwareCmsPage',
        ),
        migrations.DeleteModel(
            name='ShopwareCmsSlot',
        ),
    ]
