# Generated by Django 6.0.2 on 2026-08-05 08:37

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_shopwarecmsslot_page_document_source_docx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_docx',
            field=models.FileField(blank=True, help_text='Wird rechts als schreibgeschuetzte PDF-Vorschau angezeigt. DOCX und RTF werden direkt von LibreOffice konvertiert.', upload_to=documents.models.document_source_docx_upload_to, validators=[django.core.validators.FileExtensionValidator(['docx', 'rtf'])], verbose_name='DOCX-/RTF-Quelldatei'),
        ),
    ]
