# Generated by Django 6.0.2 on 2026-08-05 09:03

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_source_docx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_docx',
            field=models.FileField(blank=True, help_text='Optional: zum Herunterladen und Bearbeiten im jeweiligen Programm hinterlegen.', upload_to=documents.models.document_source_docx_upload_to, validators=[django.core.validators.FileExtensionValidator(['docx', 'rtf'])], verbose_name='DOCX-/RTF-Quelldatei'),
        ),
    ]
