# Generated by Django 6.0.2 on 2026-08-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_source_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shopware_cms_page_id',
            field=models.CharField(blank=True, default='', help_text='Die Erlebniswelt wird im Dokument-Admin aus Shopware ausgewählt.', max_length=64, verbose_name='Shopware Erlebniswelt-ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shopware_media_id',
            field=models.CharField(blank=True, default='', help_text='Die PDF-Mediendatei wird im Dokument-Admin aus Shopware ausgewählt.', max_length=64, verbose_name='Shopware Media-ID'),
        ),
    ]
