# Generated by Django 6.0.2 on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_shopware_cms_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shopware_media_folder_id',
            field=models.CharField(blank=True, default='', help_text='Optionaler Zielordner der PDF-Datei. Ohne Auswahl bleibt der Ordner in Shopware unverändert.', max_length=64, verbose_name='Shopware Medienordner-ID'),
        ),
    ]
