# Generated by Django 6.0.2 on 2026-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_shopware_media_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Kennung')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Freie Einstellungen dieses Dokumenttyps als JSON-Objekt.', verbose_name='Einstellungen')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Dokumenttyp',
                'verbose_name_plural': 'Dokumenttypen',
                'ordering': ('name', 'code'),
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(db_index=True, default='other', help_text='Wird im Dokument-Admin aus den gepflegten Dokumenttypen ausgewählt.', max_length=40, verbose_name='Dokumenttyp'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shopware_cms_page_id',
            field=models.CharField(blank=True, default='', help_text='Optional: Die Erlebniswelt wird im Dokument-Admin aus Shopware ausgewählt.', max_length=64, verbose_name='Shopware Erlebniswelt-ID'),
        ),
    ]
