# Generated by Django 6.0.2 on 2026-08-20 06:02

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documenttype_alter_document_document_type_and_more'),
        ('products', '0046_productvariantfamily_description_ch_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='end_pdf',
            field=models.FileField(blank=True, help_text='Wird dem generierten PDF angehängt.', upload_to=documents.models.document_end_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='End-PDF'),
        ),
        migrations.AlterField(
            model_name='document',
            name='price_list_duplicate_categories',
            field=models.ManyToManyField(blank=True, help_text='Artikel aus diesen Kategorien und ihren Unterkategorien dürfen in einer Preisliste zusätzlich zu ihrer regulären Kategorie erscheinen.', limit_choices_to={'is_active': True}, related_name='price_list_duplicate_documents', to='products.category', verbose_name='Kategorien mit Doppelauflistung'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template_file',
            field=models.FileField(blank=True, help_text='Primäre Vorlage. Eine neue Datei wird ohne Container-Neustart beim Rendern geladen.', upload_to=documents.models.document_template_upload_to, validators=[django.core.validators.FileExtensionValidator(['html', 'htm'])], verbose_name='HTML-Template-Datei'),
        ),
    ]
