# Generated by Django 6.0.2 on 2026-09-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_alter_aiproviderconfig_options_and_more'),
        ('documents', '0014_alter_document_end_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Eingefrorene Daten für reproduzierbare, erzeugte Dokumente.', verbose_name='Daten-Snapshot'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Vorlagen werden bei der Erzeugung neuer Dokumente ausgewählt und nicht selbst veröffentlicht.', verbose_name='Vorlage'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_template': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='documents.document', verbose_name='Verwendete Vorlage'),
        ),
        migrations.AddField(
            model_name='document',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig ab'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Daten-Snapshot'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig ab'),
        ),
        migrations.CreateModel(
            name='DocumentImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('queued', 'In Arbeit'), ('ready', 'Ergebnis vorhanden'), ('applied', 'Übernommen'), ('failed', 'Fehlgeschlagen')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('source_blocks', models.JSONField(blank=True, default=list, verbose_name='Extrahierte Word-Blöcke')),
                ('source_text', models.TextField(blank=True, default='', verbose_name='Quelltext')),
                ('result_html', models.TextField(blank=True, default='', verbose_name='Erzeugtes HTML')),
                ('rendered_prompt', models.TextField(blank=True, default='', verbose_name='KI-Anfrage')),
                ('provider_response', models.TextField(blank=True, default='', verbose_name='KI-Rückgabe (roh)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehler')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task-ID')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Übernommen am')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='documents.document', verbose_name='Dokument')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_import_jobs', to='ai.aiproviderconfig', verbose_name='KI')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_document_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Angefordert von')),
            ],
            options={
                'verbose_name': 'Word-Import',
                'verbose_name_plural': 'Word-Importe',
                'ordering': ('-created_at',),
            },
        ),
    ]
