# Generated by Django 6.0.2 on 2026-09-23 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_aidocumentprompt'),
        ('documents', '0015_document_context_snapshot_document_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_document_prompt',
            field=models.ForeignKey(blank=True, help_text='Optionaler Dokument-Prompt. Ohne Auswahl wird der aktive Standard-Prompt verwendet.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ai.aidocumentprompt', verbose_name='KI-Prompt für Word-Import'),
        ),
        migrations.AddField(
            model_name='documentimportjob',
            name='placeholder_values_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Verwendete Platzhalterwerte'),
        ),
        migrations.AddField(
            model_name='documentimportjob',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_import_jobs', to='ai.aidocumentprompt', verbose_name='KI-Prompt'),
        ),
        migrations.AddField(
            model_name='documentimportjob',
            name='system_prompt_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='System-Prompt zum Ausführungszeitpunkt'),
        ),
        migrations.CreateModel(
            name='DocumentPlaceholderValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('placeholder', models.CharField(help_text='Exakt wie in der Word-Datei, einschließlich der spitzen Klammern.', max_length=502, validators=[django.core.validators.RegexValidator(message='Der Platzhalter muss im Format <Bezeichnung> angegeben werden.', regex='^<[^<>\\r\\n]{2,500}>$')], verbose_name='Platzhalter')),
                ('value', models.TextField(help_text='Wird bei jedem Vorkommen dieses Platzhalters im Dokument eingesetzt.', verbose_name='Wert')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_values', to='documents.document', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Dokument-Platzhalterwert',
                'verbose_name_plural': 'Dokument-Platzhalterwerte',
                'ordering': ('document', 'placeholder'),
                'constraints': [models.UniqueConstraint(fields=('document', 'placeholder'), name='documents_unique_placeholder_per_document')],
            },
        ),
    ]
