"""
Django settings for GC_Bridge_4 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from functools import partial
from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from core.unfold import admin_model_permission

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key, value.strip().strip('"').strip("'"))

def env_url(name: str, default: str = "") -> str:
    value = os.getenv(name, default).strip()
    if not value:
        return ""
    return f"{value.rstrip('/')}/"


CDN_PREFIX = env_url("CDN_PREFIX")
MICROTECH_IMAGE_BASE_URL = env_url(
    "MICROTECH_IMAGE_BASE_URL",
    f"{CDN_PREFIX}img/" if CDN_PREFIX else "",
)
SHOPWARE_PRODUCT_MEDIA_FOLDER_ID = os.getenv("SHOPWARE_PRODUCT_MEDIA_FOLDER_ID", "").strip()


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


LOGS_ROOT = Path(os.getenv("LOGS_ROOT", "tmp/logs"))
if not LOGS_ROOT.is_absolute():
    LOGS_ROOT = BASE_DIR / LOGS_ROOT

LOG_RETENTION_DAILY = os.getenv("LOG_RETENTION_DAILY", "7 days").strip() or "7 days"
LOG_RETENTION_WEEKLY = os.getenv("LOG_RETENTION_WEEKLY", "7 days").strip() or "7 days"
LOG_RETENTION_MONTHLY = os.getenv("LOG_RETENTION_MONTHLY", "7 days").strip() or "7 days"

ADMIN_LOG_READER_FILES = env_list(
    "ADMIN_LOG_READER_FILES",
    "",
)


def sidebar_model_view_permission(app_label: str, model_name: str):
    return partial(admin_model_permission, app_label=app_label, model_name=model_name)


def sidebar_model_add_permission(app_label: str, model_name: str):
    return partial(admin_model_permission, app_label=app_label, model_name=model_name, permission="add")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-ut64(u578ew@!c##-_&(vxb&41^!1!+8_7eo+ifu6r6^k1wulc",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080",
)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'modeltranslation',
    'mptt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ai.apps.AiConfig',
    'core.apps.CoreConfig',
    'customer.apps.CustomerConfig',
    'orders.apps.OrdersConfig',
    'products.apps.ProductsConfig',
    'shopware.apps.ShopwareConfig',
    'microtech.apps.MicrotechConfig',
    'mappei.apps.MappeiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GC_Bridge_4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GC_Bridge_4.wsgi.application'
ASGI_APPLICATION = 'GC_Bridge_4.asgi.application'

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", False)
USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", True)
if env_bool("DJANGO_USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "gc_bridge_4"),
        "USER": os.getenv("POSTGRES_USER", "gc_bridge_4"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "gc_bridge_4"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de'
LANGUAGES = [
    ('de', 'Deutsch'),
    ('en', 'Englisch'),
]

SHOPWARE6_SHOP_URL = os.getenv("SHOPWARE6_SHOP_URL", "").rstrip("/")

MODELTRANSLATION_DEFAULT_LANGUAGE = 'de'
MODELTRANSLATION_LANGUAGES = ('de', 'en')
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('de',),
    'de': ('en',),
    'en': ('de',),
}

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

LOCALE_PATHS = [BASE_DIR / "locale"]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


UNFOLD = {
    "SITE_TITLE": "GC-Bridge Admin",
    "SITE_HEADER": "GC-Bridge",
    "SITE_SUBHEADER": "core.version.site_subheader_callback",
    "SITE_SYMBOL": "hub",
    "SITE_URL": "/",
    "SITE_DROPDOWN": [
        {
            "title": _("Handbuch"),
            "icon": "menu_book",
            "link": "/docs/html/index.html",
            "attrs": {
                "target": "_blank",
                "rel": "noopener noreferrer",
            },
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": False,
    "STYLES": [
        "core.unfold.admin_button_loader_style",
    ],
    "SCRIPTS": [
        "core.unfold.admin_button_loader_script",
    ],
    "ENVIRONMENT": "core.unfold.environment_callback",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "de": "DE",
                "en": "EN",
            },
        },
    },
    "COLORS": {
        "primary": {
            "50": "#fff5eb",
            "100": "#ffe8cc",
            "200": "#ffd6a3",
            "300": "#ffc278",
            "400": "#ffad52",
            "500": "#ff9933",
            "600": "#f08316",
            "700": "#cc6c10",
            "800": "#a85710",
            "900": "#8a4a12",
            "950": "#4d2608",
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "command_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Allgemein"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Bestellungen"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bestellungen"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                        "permission": sidebar_model_view_permission("orders", "Order"),
                    },
                    {
                        "title": _("Bestellpositionen"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:orders_orderdetail_changelist"),
                        "permission": sidebar_model_view_permission("orders", "OrderDetail"),
                    },
                ],
            },
            {
                "title": _("Kunden"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Kunden"),
                        "icon": "people",
                        "link": reverse_lazy("admin:customer_customer_changelist"),
                        "permission": sidebar_model_view_permission("customer", "Customer"),
                    },
                    {
                        "title": _("Adressen"),
                        "icon": "home",
                        "link": reverse_lazy("admin:customer_address_changelist"),
                        "permission": sidebar_model_view_permission("customer", "Address"),
                    },
                    {
                        "title": _("Kunden Merge"),
                        "icon": "merge",
                        "link": reverse_lazy("admin:customer_merge"),
                        "permission": sidebar_model_view_permission("customer", "Customer"),
                    },
                ],
            },
            {
                "title": _("Produkte"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Produkte"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:products_product_changelist"),
                        "permission": sidebar_model_view_permission("products", "Product"),
                    },
                    {
                        "title": _("Preise"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:products_price_changelist"),
                        "permission": sidebar_model_view_permission("products", "Price"),
                    },
                    {
                        "title": _("Preiserhöhungen"),
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:products_priceincrease_changelist"),
                        "permission": sidebar_model_view_permission("products", "PriceIncrease"),
                    },
                    {
                        "title": _("Kategorien"),
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:products_category_manager"),
                        "permission": sidebar_model_view_permission("products", "Category"),
                    },
                    {
                        "title": _("Attributgruppen"),
                        "icon": "category",
                        "link": reverse_lazy("admin:products_propertygroup_changelist"),
                        "permission": sidebar_model_view_permission("products", "PropertyGroup"),
                    },
                    {
                        "title": _("Attributwerte"),
                        "icon": "label",
                        "link": reverse_lazy("admin:products_propertyvalue_changelist"),
                        "permission": sidebar_model_view_permission("products", "PropertyValue"),
                    },
                ],
            },
            {
                "title": _("Mappei"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Produkte"),
                        "icon": "store",
                        "link": reverse_lazy("admin:mappei_mappeiproduct_changelist"),
                        "permission": sidebar_model_view_permission("mappei", "MappeiProduct"),
                    },
                    {
                        "title": _("Preise"),
                        "icon": "price_check",
                        "link": reverse_lazy("admin:mappei_mappeipricesnapshot_changelist"),
                        "permission": sidebar_model_view_permission("mappei", "MappeiPriceSnapshot"),
                    },
                    {
                        "title": _("Mappei<->Classei"),
                        "icon": "link",
                        "link": reverse_lazy("admin:mappei_mappeiproductmapping_changelist"),
                        "permission": sidebar_model_view_permission("mappei", "MappeiProductMapping"),
                    },
                ],
            },
            {
                "title": _("AI"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Rewrite erzeugen"),
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:ai_airewritejob_request"),
                        "permission": sidebar_model_add_permission("ai", "AIRewriteJob"),
                    },
                    {
                        "title": _("Rewrite Jobs"),
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:ai_airewritejob_changelist"),
                        "permission": sidebar_model_view_permission("ai", "AIRewriteJob"),
                    },
                    {
                        "title": _("Prompts"),
                        "icon": "prompt_suggestion",
                        "link": reverse_lazy("admin:ai_airewriteprompt_changelist"),
                        "permission": sidebar_model_view_permission("ai", "AIRewritePrompt"),
                    },
                    {
                        "title": _("Provider"),
                        "icon": "cloud",
                        "link": reverse_lazy("admin:ai_aiproviderconfig_changelist"),
                        "permission": sidebar_model_view_permission("ai", "AIProviderConfig"),
                    },
                ],
            },
            {
                "title": _("Shopware"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Verbindung"),
                        "icon": "cable",
                        "link": reverse_lazy("admin:shopware_shopwareconnection_changelist"),
                        "permission": sidebar_model_view_permission("shopware", "ShopwareConnection"),
                    },
                    {
                        "title": _("Verkaufskanäle"),
                        "icon": "storefront",
                        "link": reverse_lazy("admin:shopware_shopwaresettings_changelist"),
                        "permission": sidebar_model_view_permission("shopware", "ShopwareSettings"),
                    },
                ],
            },
            {
                "title": _("Microtech"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Einstellungen"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:microtech_microtechorderrule_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechOrderRule"),
                    },
                    {
                        "title": _("Verbindung"),
                        "icon": "cable",
                        "link": reverse_lazy("admin:microtech_microtechsettings_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechSettings"),
                    },
                    {
                        "title": _("Operatoren"),
                        "icon": "rule",
                        "link": reverse_lazy("admin:microtech_microtechorderruleoperator_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechOrderRuleOperator"),
                    },
                    {
                        "title": _("Django Feld Policies"),
                        "icon": "input",
                        "link": reverse_lazy("admin:microtech_microtechorderruledjangofieldpolicy_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechOrderRuleDjangoFieldPolicy"),
                    },
                    {
                        "title": _("Datasets"),
                        "icon": "storage",
                        "link": reverse_lazy("admin:microtech_microtechdatasetcatalog_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechDatasetCatalog"),
                    },
                    {
                        "title": _("Dataset Felder"),
                        "icon": "table_rows",
                        "link": reverse_lazy("admin:microtech_microtechdatasetfield_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechDatasetField"),
                    },
                    {
                        "title": _("Schweiz Zoll Mapping"),
                        "icon": "description",
                        "link": reverse_lazy("admin:microtech_microtechswisscustomsfieldmapping_changelist"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechSwissCustomsFieldMapping"),
                    },
                    {
                        "title": _("Queue"),
                        "icon": "pending_actions",
                        "link": reverse_lazy("admin:microtech_queue"),
                        "permission": sidebar_model_view_permission("microtech", "MicrotechJob"),
                    },
                ],
            },
            {
                "title": _("Verwaltung"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Benutzer"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": sidebar_model_view_permission("auth", "User"),
                    },
                    {
                        "title": _("Gruppen"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": sidebar_model_view_permission("auth", "Group"),
                    },
                    {
                        "title": _("System-Status"),
                        "icon": "monitor_heart",
                        "link": reverse_lazy("admin:core_system_status"),
                        "permission": "core.unfold.superuser_only",
                    },
                    {
                        "title": _("Logs"),
                        "icon": "article",
                        "link": reverse_lazy("admin:core_log_reader"),
                        "permission": "core.unfold.superuser_only",
                    },
                ],
            },
        ],
    },
}
