"""
Django settings for GC_Bridge_4 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key, value.strip().strip('"').strip("'"))

CDN_PREFIX = os.getenv("CDN_PREFIX", "")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-ut64(u578ew@!c##-_&(vxb&41^!1!+8_7eo+ifu6r6^k1wulc",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080",
)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'customer.apps.CustomerConfig',
    'orders.apps.OrdersConfig',
    'products.apps.ProductsConfig',
    'shopware.apps.ShopwareConfig',
    'microtech.apps.MicrotechConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GC_Bridge_4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GC_Bridge_4.wsgi.application'
ASGI_APPLICATION = 'GC_Bridge_4.asgi.application'

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", False)
USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", True)
if env_bool("DJANGO_USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "gc_bridge_4"),
        "USER": os.getenv("POSTGRES_USER", "gc_bridge_4"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "gc_bridge_4"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de'
LANGUAGES = [
    ('de', 'Deutsch'),
    ('en', 'Englisch'),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'de'
MODELTRANSLATION_LANGUAGES = ('de', 'en')
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('de',),
    'de': ('en',),
    'en': ('de',),
}

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


UNFOLD = {
    "SITE_TITLE": "GC-Bridge Admin",
    "SITE_HEADER": "GC-Bridge",
    "SITE_SUBHEADER": "Shopware <-> Microtech",
    "SITE_SYMBOL": "hub",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": False,
    "ENVIRONMENT": "core.unfold.environment_callback",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "de": "DE",
                "en": "EN",
            },
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "command_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Allgemein"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Bestellungen"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bestellungen"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Bestellpositionen"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:orders_orderdetail_changelist"),
                    },
                ],
            },
            {
                "title": _("Kunden"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Kunden"),
                        "icon": "people",
                        "link": reverse_lazy("admin:customer_customer_changelist"),
                    },
                    {
                        "title": _("Adressen"),
                        "icon": "home",
                        "link": reverse_lazy("admin:customer_address_changelist"),
                    },
                ],
            },
            {
                "title": _("Produkte"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Produkte"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:products_product_changelist"),
                    },
                    {
                        "title": _("Preise"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:products_price_changelist"),
                    },
                    {
                        "title": _("Lager"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:products_storage_changelist"),
                    },
                    {
                        "title": _("Kategorien"),
                        "icon": "category",
                        "link": reverse_lazy("admin:products_category_changelist"),
                    },
                    {
                        "title": _("Steuern"),
                        "icon": "percent",
                        "link": reverse_lazy("admin:products_tax_changelist"),
                    },
                ],
            },
            {
                "title": _("Konfiguration"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Shopware"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:shopware_shopwaresettings_changelist"),
                    },
                    {
                        "title": _("Benutzer"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": "core.unfold.superuser_only",
                    },
                    {
                        "title": _("Gruppen"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": "core.unfold.superuser_only",
                    },
                ],
            },
        ],
    },
}
