# Generated by Django 6.0.2 on 2026-06-18 11:13

import django.core.validators
import qrcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=180, verbose_name='Titel')),
                ('target_url', models.URLField(max_length=2048, verbose_name='Ziel-URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('center_mode', models.CharField(choices=[('none', 'Ohne Inhalt'), ('image', 'Bild'), ('text', 'Text')], default='none', max_length=12, verbose_name='Mitte')),
                ('center_image', models.ImageField(blank=True, upload_to=qrcodes.models.qr_center_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Bild in der Mitte')),
                ('center_text', models.CharField(blank=True, default='', max_length=80, verbose_name='Text in der Mitte')),
                ('foreground_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Bitte eine gueltige Hex-Farbe im Format #RRGGBB eingeben.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='QR-Farbe')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Bitte eine gueltige Hex-Farbe im Format #RRGGBB eingeben.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Hintergrundfarbe')),
                ('center_scale_percent', models.PositiveSmallIntegerField(default=24, help_text='Empfohlen: 18 bis 26 Prozent. Groessere Werte koennen die Lesbarkeit reduzieren.', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(32)], verbose_name='Groesse der Mitte in Prozent')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'QR-Code',
                'verbose_name_plural': 'QR-Codes',
                'ordering': ('title',),
            },
        ),
    ]
