# Generated by Django 6.0.2 on 2026-07-14 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='center_scale_percent',
            field=models.PositiveSmallIntegerField(default=16, help_text='Empfohlen: 12 bis 18 Prozent. Maximal 22 Prozent – groessere Werte machen den QR-Code unlesbar.', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(22)], verbose_name='Groesse der Mitte in Prozent'),
        ),
    ]
