# Generated by Django 6.0.2 on 2026-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('mandant', models.CharField(max_length=100, verbose_name='Mandant')),
                ('firma', models.CharField(blank=True, default='', max_length=255, verbose_name='Firma')),
                ('benutzer', models.CharField(blank=True, default='', max_length=100, verbose_name='Benutzer (Autosync)')),
                ('manual_benutzer', models.CharField(blank=True, default='', max_length=100, verbose_name='Benutzer (Manuell)')),
            ],
            options={
                'verbose_name': 'Microtech Konfiguration',
                'verbose_name_plural': 'Microtech Konfiguration',
            },
        ),
    ]
