# Generated by Django 6.0.2 on 2026-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechsettings',
            name='default_versandart_id',
            field=models.PositiveIntegerField(default=10, verbose_name='Standard Versandart-ID'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='default_vorgangsart_id',
            field=models.PositiveIntegerField(default=111, verbose_name='Standard Vorgangsart-ID'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='default_zahlungsart_id',
            field=models.PositiveIntegerField(default=22, verbose_name='Standard Zahlungsart-ID'),
        ),
    ]
