# Generated by Django 6.0.2 on 2026-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0002_microtechsettings_default_versandart_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechOrderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('customer_type', models.CharField(choices=[('any', 'Beliebig'), ('company', 'Firma'), ('private', 'Privat')], default='any', max_length=32, verbose_name='Kundentyp')),
                ('billing_country_code', models.CharField(blank=True, default='', max_length=8, verbose_name='Rechnungsland (ISO2)')),
                ('shipping_country_code', models.CharField(blank=True, default='', max_length=8, verbose_name='Lieferland (ISO2)')),
                ('country_match_mode', models.CharField(choices=[('billing_only', 'Nur Rechnungsland'), ('shipping_only', 'Nur Lieferland'), ('either', 'Rechnungs- oder Lieferland'), ('both', 'Rechnungs- und Lieferland')], default='either', max_length=32, verbose_name='Laenderabgleich')),
                ('payment_method_pattern', models.CharField(blank=True, default='', max_length=255, verbose_name='Zahlungsart enthaelt')),
                ('shipping_method_pattern', models.CharField(blank=True, default='', max_length=255, verbose_name='Versandart enthaelt')),
                ('na1_mode', models.CharField(choices=[('auto', 'Automatisch'), ('firma_or_salutation', 'Firma fuer Unternehmen, sonst Anrede'), ('salutation_only', 'Immer Anrede'), ('static', 'Statischer Text')], default='auto', max_length=32, verbose_name='Na1 Modus')),
                ('na1_static_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Na1 statischer Text')),
                ('vorgangsart_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vorgangsart-ID')),
                ('zahlungsart_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Zahlungsart-ID')),
                ('versandart_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versandart-ID')),
                ('zahlungsbedingung', models.CharField(blank=True, default='', max_length=255, verbose_name='Zahlungsbedingung')),
                ('add_payment_position', models.BooleanField(default=False, verbose_name='Zusatzposition fuer Zahlungsart anlegen')),
                ('payment_position_erp_nr', models.CharField(blank=True, default='', max_length=255, verbose_name='Zahlungs-Zusatzposition ERP-Nr')),
                ('payment_position_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Zahlungs-Zusatzposition Name')),
                ('payment_position_mode', models.CharField(choices=[('fixed', 'Fester Betrag'), ('percent_total', 'Prozent vom Bestellwert')], default='fixed', max_length=32, verbose_name='Zahlungs-Zusatzposition Modus')),
                ('payment_position_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Zahlungs-Zusatzposition Wert')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel',
                'verbose_name_plural': 'Microtech Bestellregeln',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
