# Generated by Django 6.0.2 on 2026-03-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0003_microtechorderrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderrule',
            name='condition_logic',
            field=models.CharField(choices=[('all', 'UND (&)'), ('any', 'ODER (||)')], default='all', max_length=16, verbose_name='Bedingungslogik'),
        ),
        migrations.CreateModel(
            name='MicrotechOrderRuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('target_field', models.CharField(choices=[('na1_mode', 'Na1 Modus'), ('na1_static_value', 'Na1 statischer Text'), ('vorgangsart_id', 'Vorgangsart-ID'), ('zahlungsart_id', 'Zahlungsart-ID'), ('versandart_id', 'Versandart-ID'), ('zahlungsbedingung', 'Zahlungsbedingung'), ('add_payment_position', 'Zusatzposition Zahlungsart anlegen'), ('payment_position_erp_nr', 'Zahlungs-Zusatzposition ERP-Nr'), ('payment_position_name', 'Zahlungs-Zusatzposition Name'), ('payment_position_mode', 'Zahlungs-Zusatzposition Modus'), ('payment_position_value', 'Zahlungs-Zusatzposition Wert')], max_length=64, verbose_name='Target Feld')),
                ('target_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Zielwert')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='microtech.microtechorderrule', verbose_name='Regel')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel Aktion',
                'verbose_name_plural': 'Microtech Bestellregel Aktionen',
                'ordering': ('rule', 'priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MicrotechOrderRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('source_field', models.CharField(choices=[('customer_type', 'Kundentyp'), ('billing_country_code', 'Rechnungsland (ISO2)'), ('shipping_country_code', 'Lieferland (ISO2)'), ('payment_method', 'Zahlungsart'), ('shipping_method', 'Versandart'), ('order_total', 'Bestellwert gesamt'), ('order_total_tax', 'Steuer gesamt'), ('shipping_costs', 'Versandkosten'), ('order_number', 'Bestellnummer')], max_length=64, verbose_name='Source Feld')),
                ('operator', models.CharField(choices=[('eq', '=='), ('contains', 'enthaelt'), ('gt', '>'), ('lt', '<')], default='eq', max_length=16, verbose_name='Operator')),
                ('expected_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Vergleichswert')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='microtech.microtechorderrule', verbose_name='Regel')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel Bedingung',
                'verbose_name_plural': 'Microtech Bestellregel Bedingungen',
                'ordering': ('rule', 'priority', 'id'),
            },
        ),
    ]
