# Generated by Django 6.0.2 on 2026-03-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0004_microtechorderrule_condition_logic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='add_payment_position',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='billing_country_code',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='country_match_mode',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='na1_mode',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='na1_static_value',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='payment_method_pattern',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='payment_position_erp_nr',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='payment_position_mode',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='payment_position_name',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='payment_position_value',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='shipping_country_code',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='shipping_method_pattern',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='versandart_id',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='vorgangsart_id',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='zahlungsart_id',
        ),
        migrations.RemoveField(
            model_name='microtechorderrule',
            name='zahlungsbedingung',
        ),
    ]
