# Generated by Django 6.0.2 on 2026-03-04 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0005_remove_microtechorderrule_add_payment_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('job_type', models.CharField(choices=[('sync_products', 'Produkte synchronisieren'), ('lookup_article', 'Artikel nachschlagen'), ('sync_customer', 'Kunde aus Microtech laden'), ('upsert_customer', 'Kunde nach Microtech schreiben'), ('upsert_order', 'Bestellung nach Microtech schreiben'), ('sync_expired_specials', 'Abgelaufene Sonderpreise zu Microtech schreiben')], max_length=64, verbose_name='Job-Typ')),
                ('status', models.CharField(choices=[('queued', 'In Warteschlange'), ('running', 'In Bearbeitung'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Prioritaet')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Ergebnis')),
                ('attempt', models.PositiveIntegerField(default=0, verbose_name='Versuche')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max. Retries')),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fruehester Start')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('worker_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Worker-ID')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Korrelation')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Letzter Fehler')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microtech_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Microtech Job',
                'verbose_name_plural': 'Microtech Jobs',
                'ordering': ('priority', 'run_after', 'created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'run_after', 'priority', 'id'], name='microtech_job_queue_idx'), models.Index(fields=['job_type', 'status'], name='microtech_job_type_status_idx')],
            },
        ),
    ]
