# Generated by Django 6.0.2 on 2026-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0007_delete_microtechjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechOrderRuleActionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('engine_target_field', models.CharField(choices=[('na1_mode', 'Na1 Modus'), ('na1_static_value', 'Na1 statischer Text'), ('vorgangsart_id', 'Vorgangsart-ID'), ('zahlungsart_id', 'Zahlungsart-ID'), ('versandart_id', 'Versandart-ID'), ('zahlungsbedingung', 'Zahlungsbedingung'), ('add_payment_position', 'Zusatzposition Zahlungsart anlegen'), ('payment_position_erp_nr', 'Zahlungs-Zusatzposition ERP-Nr'), ('payment_position_name', 'Zahlungs-Zusatzposition Name'), ('payment_position_mode', 'Zahlungs-Zusatzposition Modus'), ('payment_position_value', 'Zahlungs-Zusatzposition Wert')], max_length=64, verbose_name='Engine Target Feld')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('int', 'Ganzzahl'), ('decimal', 'Dezimalzahl'), ('bool', 'Bool'), ('enum', 'Enum')], default='string', max_length=32, verbose_name='Wertetyp')),
                ('enum_values', models.CharField(blank=True, default='', max_length=255, verbose_name='Enum Werte (kommagetrennt)')),
                ('hint', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('example', models.CharField(blank=True, default='', max_length=255, verbose_name='Beispiel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel Target Feld',
                'verbose_name_plural': 'Microtech Bestellregel Target Felder',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MicrotechOrderRuleOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('engine_operator', models.CharField(choices=[('eq', '=='), ('contains', 'enthaelt'), ('gt', '>'), ('lt', '<')], default='eq', max_length=16, verbose_name='Engine Operator')),
                ('hint', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel Operator',
                'verbose_name_plural': 'Microtech Bestellregel Operatoren',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='microtechorderruleaction',
            name='target_field',
            field=models.CharField(max_length=64, verbose_name='Target Feld'),
        ),
        migrations.AlterField(
            model_name='microtechorderrulecondition',
            name='operator',
            field=models.CharField(default='eq', max_length=16, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='microtechorderrulecondition',
            name='source_field',
            field=models.CharField(max_length=64, verbose_name='Source Feld'),
        ),
        migrations.CreateModel(
            name='MicrotechOrderRuleConditionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('engine_source_field', models.CharField(choices=[('customer_type', 'Kundentyp'), ('billing_country_code', 'Rechnungsland (ISO2)'), ('shipping_country_code', 'Lieferland (ISO2)'), ('payment_method', 'Zahlungsart'), ('shipping_method', 'Versandart'), ('order_total', 'Bestellwert gesamt'), ('order_total_tax', 'Steuer gesamt'), ('shipping_costs', 'Versandkosten'), ('order_number', 'Bestellnummer')], max_length=64, verbose_name='Engine Source Feld')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('decimal', 'Dezimalzahl'), ('enum', 'Enum'), ('country_code', 'ISO2-Laendercode')], default='string', max_length=32, verbose_name='Wertetyp')),
                ('hint', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('example', models.CharField(blank=True, default='', max_length=255, verbose_name='Beispiel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('operators', models.ManyToManyField(blank=True, related_name='condition_sources', to='microtech.microtechorderruleoperator', verbose_name='Erlaubte Operatoren')),
            ],
            options={
                'verbose_name': 'Microtech Bestellregel Source Feld',
                'verbose_name_plural': 'Microtech Bestellregel Source Felder',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
