# Generated by Django 6.0.2 on 2026-03-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0008_microtechorderruleactiontarget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechDatasetCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Dataset Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung')),
                ('source_identifier', models.CharField(max_length=255, unique=True, verbose_name='Source Identifier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Microtech Dataset',
                'verbose_name_plural': 'Microtech Datasets',
                'ordering': ('priority', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MicrotechDatasetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('field_name', models.CharField(max_length=128, verbose_name='Feldname')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung')),
                ('field_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Feldtyp')),
                ('is_calc_field', models.BooleanField(default=False, verbose_name='Berechnetes Feld')),
                ('can_access', models.BooleanField(default=True, verbose_name='Lesbar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='microtech.microtechdatasetcatalog', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Microtech Dataset Feld',
                'verbose_name_plural': 'Microtech Dataset Felder',
                'ordering': ('dataset__priority', 'dataset_id', 'priority', 'field_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='microtechorderruleactiontarget',
            name='dataset_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_targets', to='microtech.microtechdatasetfield', verbose_name='Dataset Feld (Katalog)'),
        ),
        migrations.AddField(
            model_name='microtechorderruleconditionsource',
            name='dataset_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_sources', to='microtech.microtechdatasetfield', verbose_name='Dataset Feld (Katalog)'),
        ),
        migrations.AddConstraint(
            model_name='microtechdatasetfield',
            constraint=models.UniqueConstraint(fields=('dataset', 'field_name'), name='unique_microtech_dataset_field_name'),
        ),
    ]
