# Generated by Django 6.0.2 on 2026-03-10 10:19

from django.db import migrations


def reset_rulebuilder_data(apps, schema_editor):
    MicrotechOrderRule = apps.get_model("microtech", "MicrotechOrderRule")
    MicrotechOrderRuleCondition = apps.get_model("microtech", "MicrotechOrderRuleCondition")
    MicrotechOrderRuleAction = apps.get_model("microtech", "MicrotechOrderRuleAction")
    MicrotechOrderRuleDjangoFieldPolicy = apps.get_model("microtech", "MicrotechOrderRuleDjangoFieldPolicy")

    MicrotechOrderRuleCondition.objects.all().delete()
    MicrotechOrderRuleAction.objects.all().delete()
    MicrotechOrderRule.objects.all().delete()
    MicrotechOrderRuleDjangoFieldPolicy.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0010_remove_microtechorderruleconditionsource_dataset_field_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_rulebuilder_data, migrations.RunPython.noop),
    ]
