# Generated by Django 6.0.2 on 2026-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0011_reset_rulebuilder_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('queued', 'Wartend'), ('running', 'Laufend'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Prioritaet')),
                ('label', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('correlation_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Correlation ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Letzter Fehler')),
            ],
            options={
                'verbose_name': 'Microtech Job',
                'verbose_name_plural': 'Microtech Jobs',
                'ordering': ('priority', 'created_at'),
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='microtech_m_status_cde1c0_idx')],
            },
        ),
    ]
