# Generated by Django 6.0.2 on 2026-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0014_alter_microtechorderruleoperator_engine_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechorderruleoperator',
            name='engine_operator',
            field=models.CharField(choices=[('eq', '=='), ('ne', '!='), ('contains', 'enthaelt'), ('gt', '>'), ('lt', '<'), ('is_empty', 'ist leer'), ('is_not_empty', 'ist nicht leer')], default='eq', max_length=16, verbose_name='Engine Operator'),
        ),
    ]
