# Generated by Django 6.0.2 on 2026-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0015_alter_microtechorderruleoperator_engine_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechOrderRuleDjangoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('field_path', models.CharField(max_length=255, unique=True, verbose_name='Django Feldpfad')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('value_kind', models.CharField(max_length=32, verbose_name='Wertetyp')),
                ('hint', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('example', models.CharField(blank=True, default='', max_length=255, verbose_name='Beispiel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Microtech Django Feldkatalog',
                'verbose_name_plural': 'Microtech Django Feldkatalog',
                'ordering': ('priority', 'field_path', 'id'),
            },
        ),
    ]
