# Generated by Django 6.0.2 on 2026-03-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0017_microtechorderrulecondition_django_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderrulecondition',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_conditions', to='microtech.microtechorderruleoperator', verbose_name='Operator'),
        ),
    ]
