# Generated by Django 6.0.2 on 2026-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0018_microtechorderrulecondition_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechSwissCustomsFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('portal_field', models.CharField(max_length=255, unique=True, verbose_name='Portal Feld')),
                ('section', models.CharField(choices=[('shipment', 'Sendung'), ('exporter_address', 'Exporteur Adresse'), ('exporter_contact', 'Exporteur Kontakt'), ('exporter_customs', 'Exporteur Zolldaten'), ('importer_address', 'Importeur Adresse'), ('importer_contact', 'Importeur Kontakt'), ('importer_customs', 'Importeur Zolldaten'), ('consignee_address', 'Empfaenger Adresse'), ('consignee_contact', 'Empfaenger Kontakt'), ('invoice', 'Rechnung'), ('line_item', 'Position'), ('line_item_preference', 'Position Praeferenz'), ('line_item_national_customs', 'Position nationale Zolldaten')], default='shipment', max_length=48, verbose_name='Bereich')),
                ('source_type', models.CharField(choices=[('static', 'Statischer Wert'), ('order', 'Bestellung'), ('customer', 'Kunde'), ('billing_address', 'Rechnungsadresse'), ('shipping_address', 'Lieferadresse'), ('order_detail', 'Bestellposition'), ('product', 'Produkt'), ('computed', 'Berechneter Resolver')], default='static', max_length=32, verbose_name='Quelltyp')),
                ('source_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Quellpfad / Resolver')),
                ('static_value', models.TextField(blank=True, default='', verbose_name='Statischer Wert')),
                ('value_kind', models.CharField(blank=True, default='text', max_length=32, verbose_name='Wertetyp')),
                ('is_required', models.BooleanField(default=False, verbose_name='Pflichtfeld')),
                ('help_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Hinweis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Microtech Schweiz Zoll Feldmapping',
                'verbose_name_plural': 'Microtech Schweiz Zoll Feldmappings',
                'ordering': ('priority', 'portal_field', 'id'),
            },
        ),
    ]
