# Generated by Django 6.0.2 on 2026-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0019_microtechswisscustomsfieldmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechswisscustomsfieldmapping',
            name='static_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Statischer Wert'),
        ),
    ]
