# Generated by Django 6.0.2 on 2026-05-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0020_alter_microtechswisscustomsfieldmapping_static_value'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='microtechjob',
            name='microtech_m_status_cde1c0_idx',
        ),
        migrations.DeleteModel(
            name='MicrotechJob',
        ),
    ]
