# Generated by Django 6.0.2 on 2026-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0021_remove_microtechjob_microtech_m_status_cde1c0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechGraphQLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('kind', models.CharField(choices=[('dataset_records', 'Dataset lesen'), ('product_read', 'Produkt lesen'), ('product_update', 'Produkt aktualisieren'), ('customer_read', 'Kunde lesen'), ('customer_upsert', 'Kunde schreiben'), ('order_read', 'Vorgang lesen'), ('order_upsert', 'Vorgang schreiben'), ('maintenance', 'Wartung'), ('custom', 'Benutzerdefiniert')], db_index=True, max_length=48, verbose_name='Job-Art')),
                ('operation', models.CharField(db_index=True, max_length=96, verbose_name='GraphQL Operation')),
                ('status', models.CharField(choices=[('queued', 'Wartend'), ('submitted', 'An GraphQL uebergeben'), ('running', 'Laeuft'), ('waiting_webhook', 'Wartet auf Webhook'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('cancel_requested', 'Abbruch angefordert'), ('cancelled', 'Abgebrochen'), ('delete_failed', 'Remote-Loeschung fehlgeschlagen')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='GraphQL Job-ID')),
                ('continuation', models.CharField(blank=True, default='', max_length=96, verbose_name='Continuation')),
                ('next_step', models.CharField(blank=True, default='', max_length=255, verbose_name='Naechster Schritt')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request Payload')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Kontext')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Ergebnis Payload')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehler')),
                ('abort_strategy', models.CharField(choices=[('cancel_then_delete', 'Remote abbrechen, dann loeschen'), ('delete_remote', 'Remote loeschen'), ('local_only', 'Nur lokal abbrechen')], default='cancel_then_delete', max_length=32, verbose_name='Abbruchstrategie')),
                ('delete_after_completion', models.BooleanField(default=True, verbose_name='Nach Abschluss loeschen')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Uebergeben am')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Webhook erhalten am')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt abgefragt am')),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Naechster Poll')),
                ('remote_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Remote geloescht am')),
                ('attempt', models.PositiveIntegerField(default=0, verbose_name='Versuche')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max. Versuche')),
            ],
            options={
                'verbose_name': 'Microtech GraphQL Job',
                'verbose_name_plural': 'Microtech GraphQL Jobs',
                'ordering': ('status', 'submitted_at', 'created_at'),
                'indexes': [models.Index(fields=['status', 'next_poll_at'], name='microtech_gql_job_poll_idx'), models.Index(fields=['kind', 'status'], name='microtech_gql_job_kind_idx')],
            },
        ),
    ]
