# Generated by Django 6.0.2 on 2026-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0022_microtechgraphqljob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microtechsettings',
            name='benutzer',
        ),
        migrations.RemoveField(
            model_name='microtechsettings',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='microtechsettings',
            name='mandant',
        ),
        migrations.RemoveField(
            model_name='microtechsettings',
            name='manual_benutzer',
        ),
    ]
