# Generated by Django 6.0.2 on 2026-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0023_remove_microtechsettings_benutzer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechsettings',
            name='backup_mode_active',
            field=models.BooleanField(default=False, verbose_name='Backup-Fenster aktiv'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='backup_mode_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Backup-Fenster Frist'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='backup_mode_entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Backup-Fenster geoeffnet am'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='backup_mode_started_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Backup-Fenster geoeffnet von'),
        ),
    ]
