# Generated by Django 6.0.2 on 2026-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0025_backup_mode_watchdog_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechorderruleaction',
            name='action_type',
            field=models.CharField(choices=[('set_field', 'Dataset Feld setzen'), ('create_extra_position', 'Zusatzposition anlegen'), ('create_shipping_position', 'Versandposition anlegen')], default='set_field', max_length=32, verbose_name='Aktionstyp'),
        ),
    ]
