# Generated by Django 6.0.2 on 2026-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0026_alter_microtechorderruleaction_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('task_name', models.CharField(db_index=True, max_length=128, verbose_name='Celery Task')),
                ('context_root', models.CharField(max_length=128, verbose_name='Kontext-Wurzel (app_label.Model)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
            ],
            options={
                'verbose_name': 'Regel-Trigger',
                'verbose_name_plural': 'Regel-Trigger',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
