# Generated by Django 6.0.2 on 2026-08-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0027_ruletrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderrule',
            name='engine_enabled',
            field=models.BooleanField(default=False, verbose_name='Neue Engine aktiv'),
        ),
        migrations.AddField(
            model_name='microtechorderrule',
            name='execution_phase',
            field=models.CharField(choices=[('before', 'Vor dem Task'), ('after', 'Nach dem Task')], default='before', max_length=16, verbose_name='Ausfuehrungsphase'),
        ),
        migrations.AddField(
            model_name='microtechorderrule',
            name='shadow_mode',
            field=models.BooleanField(default=True, verbose_name='Schatten-Modus'),
        ),
        migrations.AddField(
            model_name='microtechorderrule',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='microtech.ruletrigger', verbose_name='Trigger'),
        ),
    ]
