# Generated by Django 6.0.2 on 2026-08-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0028_microtechorderrule_engine_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderrulecondition',
            name='expected_value_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vergleichswert 2'),
        ),
        migrations.CreateModel(
            name='MicrotechOrderRuleConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('logic', models.CharField(choices=[('all', 'UND (&)'), ('any', 'ODER (||)')], default='all', max_length=16, verbose_name='Logik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Prioritaet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='microtech.microtechorderruleconditiongroup', verbose_name='Uebergeordnete Gruppe')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='microtech.microtechorderrule', verbose_name='Regel')),
            ],
            options={
                'verbose_name': 'Bedingungsgruppe',
                'verbose_name_plural': 'Bedingungsgruppen',
                'ordering': ('rule', 'priority', 'id'),
            },
        ),
        migrations.AddField(
            model_name='microtechorderrulecondition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='microtech.microtechorderruleconditiongroup', verbose_name='Gruppe'),
        ),
    ]
