# Generated by Django 6.0.2 on 2026-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0031_seed_engine_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Schluessel')),
                ('value', models.TextField(blank=True, default='', verbose_name='Wert')),
                ('kind', models.CharField(choices=[('scalar', 'Einzelwert'), ('list', 'Liste (komma-separiert)')], default='scalar', max_length=16, verbose_name='Art')),
            ],
            options={
                'verbose_name': 'Regel-Konstante',
                'verbose_name_plural': 'Regel-Konstanten',
                'ordering': ('key',),
            },
        ),
    ]
