# Generated by Django 6.0.2 on 2026-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0035_migrate_flat_conditions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_attempt',
            field=models.PositiveIntegerField(default=0, verbose_name='Continuation-Versuche'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Continuation abgeschlossen am'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Continuation eingereiht am'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Continuation Heartbeat'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Continuation-Lease bis'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Continuation max. Versuche'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Continuation gestartet am'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('dispatched', 'Eingereiht'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], db_index=True, default='pending', max_length=16, verbose_name='Continuation-Status'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='continuation_task_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Continuation Celery-Task-ID'),
        ),
        migrations.AddIndex(
            model_name='microtechgraphqljob',
            index=models.Index(fields=['continuation_status', 'continuation_lease_expires_at'], name='microtech_gql_cont_lease_idx'),
        ),
    ]
