# Generated by Django 6.0.2 on 2026-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0036_microtechgraphqljob_continuation_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='external_job_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historie externer GraphQL-Job-IDs'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='remote_resubmit_attempt',
            field=models.PositiveIntegerField(default=0, verbose_name='Remote-Resubmits'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='remote_resubmit_max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Remote max. Resubmits'),
        ),
    ]
