# Generated by Django 6.0.2 on 2026-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0037_remote_job_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEngineShadowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('order_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Bestellnummer')),
                ('task_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Trigger-Task')),
                ('engine_rule_id', models.IntegerField(blank=True, null=True, verbose_name='Engine-Regel-ID')),
                ('legacy_rule_id', models.IntegerField(blank=True, null=True, verbose_name='Legacy-Regel-ID')),
                ('is_equal', models.BooleanField(default=True, verbose_name='Übereinstimmung')),
                ('changed_json', models.TextField(blank=True, default='', verbose_name='Abweichungen (JSON)')),
            ],
            options={
                'verbose_name': 'Regel-Engine Schatten-Lauf',
                'verbose_name_plural': 'Regel-Engine Schatten-Läufe',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='rule_engine_order_mode',
            field=models.CharField(choices=[('off', 'Aus (nur alter Resolver)'), ('shadow', 'Schatten (alt maßgeblich, Engine vergleicht)'), ('live', 'Live (neue Engine maßgeblich)')], default='off', max_length=10, verbose_name='Regel-Engine Modus (Bestellungen)'),
        ),
    ]
