# Generated by Django 6.0.2 on 2026-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0039_seed_anreden_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechorderruleoperator',
            name='engine_operator',
            field=models.CharField(choices=[('eq', '=='), ('ne', '!='), ('contains', 'enthaelt'), ('gt', '>'), ('lt', '<'), ('is_empty', 'ist leer'), ('is_not_empty', 'ist nicht leer'), ('between', 'zwischen'), ('before', 'vor'), ('after', 'nach'), ('is_true', 'ist wahr'), ('is_false', 'ist falsch'), ('in_list', 'ist in Liste'), ('not_in_list', 'ist nicht in Liste')], default='eq', max_length=16, verbose_name='Engine Operator'),
        ),
    ]
