# Generated by Django 6.0.2 on 2026-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0041_seed_list_operators_and_address_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechsettings',
            name='rule_engine_address_mode',
            field=models.CharField(choices=[('off', 'Aus (nur alter Resolver)'), ('shadow', 'Schatten (alt maßgeblich, Engine vergleicht)'), ('live', 'Live (neue Engine maßgeblich)')], default='off', max_length=10, verbose_name='Regel-Engine Modus (Anschriften)'),
        ),
    ]
