# Generated by Django 6.0.2 on 2026-09-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0042_microtechsettings_rule_engine_address_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderruleaction',
            name='graphql_field',
            field=models.CharField(blank=True, default='', help_text="Ziel im GraphQL-Schema, Form 'InputType.feld' (z. B. PostalAddressInput.name1).", max_length=128, verbose_name='GraphQL-Feld'),
        ),
    ]
