# Generated by Django 6.0.2 on 2026-09-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0043_microtechorderruleaction_graphql_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechsettings',
            name='rule_engine_customer_mode',
            field=models.CharField(choices=[('off', 'Aus (nur alter Resolver)'), ('shadow', 'Schatten (alt maßgeblich, Engine vergleicht)'), ('live', 'Live (neue Engine maßgeblich)')], default='off', max_length=10, verbose_name='Regel-Engine Modus (Kunden)'),
        ),
    ]
