# Generated by Django 6.0.2 on 2026-09-17 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0044_microtechsettings_rule_engine_customer_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEngineExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Lauf-ID')),
                ('task_name', models.CharField(db_index=True, max_length=128, verbose_name='Trigger-Task')),
                ('execution_phase', models.CharField(max_length=16, verbose_name='Phase')),
                ('engine_mode', models.CharField(max_length=10, verbose_name='Engine-Modus')),
                ('subject', models.CharField(blank=True, default='', max_length=128, verbose_name='Auslöser')),
                ('rule_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Regelname')),
                ('outcome', models.CharField(choices=[('applied', 'Ausgeführt'), ('matched_shadow', 'Trifft zu (Schattenmodus)'), ('skipped_conditions', 'Übersprungen: Bedingungen nicht erfüllt'), ('skipped_inactive', 'Übersprungen: Regel inaktiv'), ('skipped_engine_disabled', 'Übersprungen: Engine an der Regel aus'), ('skipped_mode_off', 'Übersprungen: Engine-Modus aus'), ('skipped_no_actions', 'Übersprungen: keine aktive Aktion')], db_index=True, max_length=32, verbose_name='Ergebnis')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Begründung')),
                ('actions_json', models.TextField(blank=True, default='', verbose_name='Ausgeführte Aktionen (JSON)')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='microtech.microtechorderrule', verbose_name='Regel')),
            ],
            options={
                'verbose_name': 'Regel-Engine Ausführung',
                'verbose_name_plural': 'Regel-Engine Ausführungen',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['task_name', 'created_at'], name='microtech_r_task_na_608a51_idx')],
            },
        ),
    ]
