# Generated by Django 6.0.2 on 2026-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0045_ruleengineexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleengineexecutionlog',
            name='conditions_json',
            field=models.TextField(blank=True, default='', verbose_name='Geprüfte Bedingungen (JSON)'),
        ),
    ]
