# Generated by Django 6.0.2 on 2026-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0046_ruleengineexecutionlog_conditions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderruleaction',
            name='target_scope',
            field=models.CharField(choices=[('customer', 'Kundenstamm'), ('shipping_address', 'Lieferanschrift'), ('billing_address', 'Rechnungsanschrift'), ('shipping_contact', 'Lieferansprechpartner'), ('billing_contact', 'Rechnungsansprechpartner')], default='customer', help_text='Beim Kunden-Upsert bestimmt dieser Bereich die konkrete Anschrift oder den Ansprechpartner.', max_length=32, verbose_name='Zielbereich'),
        ),
    ]
