# Generated by Django 6.0.2 on 2026-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0047_microtechorderruleaction_target_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='next_submit_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Naechste GraphQL-Uebergabe'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='submission_attempt',
            field=models.PositiveIntegerField(default=0, verbose_name='Submit-Versuche'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='submission_lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Submit-Lease bis'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='submission_max_attempts',
            field=models.PositiveIntegerField(default=5, verbose_name='Max. Submit-Versuche'),
        ),
        migrations.AddField(
            model_name='microtechgraphqljob',
            name='submission_task_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Submit Celery-Task-ID'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='graphql_circuit_open_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GraphQL Circuit Breaker offen bis'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='graphql_consecutive_failures',
            field=models.PositiveIntegerField(default=0, verbose_name='GraphQL aufeinanderfolgende Transportfehler'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='graphql_last_error',
            field=models.TextField(blank=True, default='', verbose_name='Letzter GraphQL-Transportfehlertext'),
        ),
        migrations.AddField(
            model_name='microtechsettings',
            name='graphql_last_failure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter GraphQL-Transportfehler'),
        ),
        migrations.AddIndex(
            model_name='microtechgraphqljob',
            index=models.Index(fields=['status', 'next_submit_at'], name='microtech_gql_job_submit_idx'),
        ),
    ]
