# Generated by Django 6.0.2 on 2026-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0048_microtechgraphqljob_next_submit_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechorderruleaction',
            name='action_type',
            field=models.CharField(choices=[('set_field', 'Dataset Feld setzen'), ('create_extra_position', 'Zusatzposition anlegen'), ('create_text_position', 'Textposition anlegen'), ('create_shipping_position', 'Versandposition anlegen')], default='set_field', max_length=32, verbose_name='Aktionstyp'),
        ),
    ]
