# Generated by Django 6.0.2 on 2026-09-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0049_alter_microtechorderruleaction_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechOrderRuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Reihenfolge')),
                ('is_system', models.BooleanField(default=False, verbose_name='Systemkategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Regel-Mapping Kategorie',
                'verbose_name_plural': 'Regel-Mapping Kategorien',
                'ordering': ('priority', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='microtechorderrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='microtech.microtechorderrulecategory', verbose_name='Kategorie'),
        ),
    ]
