# Generated by Django 6.0.2 on 2026-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0050_microtechorderrulecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtechorderrule',
            name='system_key',
            field=models.CharField(blank=True, editable=False, help_text='Stabile Kennung für automatisch angelegte Standardmapping-Regeln.', max_length=128, null=True, unique=True, verbose_name='Systemschlüssel'),
        ),
        migrations.AlterField(
            model_name='microtechorderruleaction',
            name='target_scope',
            field=models.CharField(choices=[('customer', 'Kundenstamm'), ('shipping_address', 'Lieferanschrift'), ('billing_address', 'Rechnungsanschrift'), ('shipping_contact', 'Lieferansprechpartner'), ('billing_contact', 'Rechnungsansprechpartner'), ('customer_defaults', 'Kundenstandardwerte'), ('order', 'Vorgang'), ('position', 'Position')], default='customer', help_text='Bestimmt den konkreten Zielbereich des Mappings.', max_length=32, verbose_name='Zielbereich'),
        ),
    ]
