# Generated by Django 6.0.2 on 2026-09-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0051_microtechorderrule_system_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechorderruleaction',
            name='target_scope',
            field=models.CharField(choices=[('customer', 'Kundenstamm'), ('shipping_address', 'Lieferanschrift'), ('billing_address', 'Rechnungsanschrift'), ('shipping_contact', 'Lieferansprechpartner'), ('billing_contact', 'Rechnungsansprechpartner'), ('customer_defaults', 'Kundenstandardwerte'), ('order', 'Vorgang'), ('position', 'Position'), ('product', 'Artikel')], default='customer', help_text='Bestimmt den konkreten Zielbereich des Mappings.', max_length=32, verbose_name='Zielbereich'),
        ),
    ]
