# Generated by Django 6.0.2 on 2026-04-15 07:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('base_url', models.URLField(blank=True, default='https://api.openai.com/v1', max_length=255, verbose_name='Base URL')),
                ('model_name', models.CharField(max_length=120, verbose_name='Modellname')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API-Key')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='Timeout (Sekunden)')),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=4, verbose_name='Temperature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Provider',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AIRewritePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('source_field', models.CharField(max_length=120, verbose_name='Quellfeld')),
                ('target_field', models.CharField(max_length=120, verbose_name='Zielfeld')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
                ('user_prompt_template', models.TextField(blank=True, default='', help_text='Optional. Wenn leer, wird ein Standard-Template verwendet.', verbose_name='User Prompt Template')),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('html', 'HTML')], default='html', max_length=20, verbose_name='Ausgabeformat')),
                ('temperature_override', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature Override')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_rewrite_prompts', to='contenttypes.contenttype', verbose_name='Modell')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='ai.aiproviderconfig', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'AI Rewrite Prompt',
                'verbose_name_plural': 'AI Rewrite Prompts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AIRewriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Objekt-ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Objekt')),
                ('source_field', models.CharField(max_length=120, verbose_name='Quellfeld')),
                ('target_field', models.CharField(max_length=120, verbose_name='Zielfeld')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending_review', 'Zur Freigabe'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('applied', 'Uebernommen'), ('failed', 'Fehlgeschlagen')], db_index=True, default='pending_review', max_length=32, verbose_name='Status')),
                ('source_snapshot', models.TextField(blank=True, default='', verbose_name='Quellinhalt')),
                ('rendered_prompt', models.TextField(blank=True, default='', verbose_name='Gerenderter Prompt')),
                ('result_text', models.TextField(blank=True, default='', verbose_name='Ergebnis')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehler')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Uebernommen am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_rewrite_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_rewrite_jobs', to='contenttypes.contenttype', verbose_name='Modell')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ai.aiproviderconfig', verbose_name='Provider')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_rewrite_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Angefordert von')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ai.airewriteprompt', verbose_name='Prompt')),
            ],
            options={
                'verbose_name': 'AI Rewrite Job',
                'verbose_name_plural': 'AI Rewrite Jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ai_airewrit_content_e4bda1_idx')],
            },
        ),
    ]
