# Generated by Django 6.0.2 on 2026-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airewritejob',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archiviert'),
        ),
    ]
