# Generated by Django 6.0.2 on 2026-07-14 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_ai_rewriter_redesign'),
        ('products', '0036_category_is_active_category_is_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airewritejob',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ai.aiproviderconfig', verbose_name='KI'),
        ),
        migrations.AddIndex(
            model_name='airewritejob',
            index=models.Index(fields=['product', 'field'], name='ai_airewrit_product_32a540_idx'),
        ),
    ]
