# Generated by Django 6.0.2 on 2026-07-14 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_add_product_field_index'),
        ('products', '0036_category_is_active_category_is_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airewritejob',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_rewrite_jobs', to='products.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='airewritejob',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_rewrite_jobs', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AddIndex(
            model_name='airewritejob',
            index=models.Index(fields=['category', 'field'], name='ai_airewrit_categor_ab20a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='airewritejob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('product__isnull', False)), models.Q(('category__isnull', False), ('product__isnull', True)), _connector='OR'), name='ai_rewrite_job_has_one_target'),
        ),
    ]
