# Generated by Django 6.0.2 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_airewritejob_category_alter_airewritejob_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airewritejob',
            name='provider_response',
            field=models.TextField(blank=True, default='', verbose_name='KI-Rueckgabe (roh)'),
        ),
    ]
