# Generated by Django 6.0.2 on 2026-08-06 11:05

import ai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_airewritejob_provider_response'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITranslationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('source_language', models.CharField(default='de', max_length=16, verbose_name='Quellsprache')),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Begrenzt die Anzahl einzelner Feld-/Sprachuebersetzungen je Scan.', verbose_name='Maximale Uebersetzungen pro Lauf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('clear_target_on_empty_source', models.BooleanField(default=True, help_text='Entfernt vorhandene Zieltexte, wenn der deutsche Quelltext geleert wurde.', verbose_name='Ziel bei leerem Quelltext leeren')),
                ('system_prompt', models.TextField(default='Du bist ein praeziser Fachuebersetzer.\n\nUebersetze ausschliesslich die Werte des uebergebenen JSON-Objekts. Halte dich eng und vollstaendig an den deutschen Originaltext: keine kreativen Umformulierungen, keine Ergaenzungen, keine Kuerzungen, keine SEO-Optimierung und keine Erklaerungen.\n\nDie JSON-Schluessel sind technische Segment-IDs. Sie muessen unveraendert bleiben. Gib ausschliesslich ein JSON-Objekt mit exakt denselben Schluesseln und den uebersetzten Textwerten zurueck. Gib kein Markdown und keinen weiteren Text aus.\n\nHTML-Markup, Attribute, CSS-Klassen, Styles, URLs und IDs werden ausserhalb des Modells erhalten. Die Segmentwerte duerfen deshalb keine HTML-Tags enthalten. HTML-Entities innerhalb eines Segmentwerts (zum Beispiel &nbsp;) muessen unveraendert erhalten bleiben.\n', verbose_name='System-Prompt')),
                ('user_prompt_template', models.TextField(default='Uebersetze die Textsegmente eines einzelnen Feldes.\n\nQuellsprache: {{ source_language_name }} ({{ source_language }})\nZielsprache: {{ target_language_name }} ({{ target_language }})\nSprachvariante: {{ locale_instruction }}\n\nTextsegmente (JSON):\n{{ segments_json }}\n', help_text='Verfuegbare Platzhalter: source_language, source_language_name, target_language, target_language_name, locale_instruction und segments_json.', verbose_name='Benutzer-Prompt-Vorlage')),
                ('locale_instructions', models.JSONField(blank=True, default=ai.models.default_translation_locale_instructions, help_text='JSON-Objekt mit Sprachcode als Schluessel und Uebersetzungshinweis als Wert.', verbose_name='Sprachvarianten-Hinweise')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_configs', to='ai.aiproviderconfig', verbose_name='KI')),
            ],
            options={
                'verbose_name': 'KI-Uebersetzungskonfiguration',
                'verbose_name_plural': 'KI-Uebersetzungskonfigurationen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AITranslationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Objekt-ID')),
                ('source_field', models.CharField(max_length=120, verbose_name='Quellfeld')),
                ('target_language', models.CharField(max_length=16, verbose_name='Zielsprache')),
                ('source_hash', models.CharField(max_length=64, verbose_name='Quell-Hash')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('running', 'Laufend'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Versuche')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task-ID')),
                ('translated_at', models.DateTimeField(blank=True, null=True, verbose_name='Uebersetzt am')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Letzter Fehler')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_states', to='ai.aitranslationconfig', verbose_name='Konfiguration')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_translation_states', to='contenttypes.contenttype', verbose_name='Objekttyp')),
            ],
            options={
                'verbose_name': 'KI-Uebersetzungsstatus',
                'verbose_name_plural': 'KI-Uebersetzungsstatus',
                'ordering': ('status', 'updated_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='aitranslationconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='ai_translation_single_active_config'),
        ),
        migrations.AddIndex(
            model_name='aitranslationstate',
            index=models.Index(fields=['content_type', 'object_id'], name='ai_aitransl_content_c42836_idx'),
        ),
        migrations.AddIndex(
            model_name='aitranslationstate',
            index=models.Index(fields=['status', 'updated_at'], name='ai_aitransl_status_54eb4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='aitranslationstate',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'source_field', 'target_language'), name='ai_translation_state_unique_target'),
        ),
    ]
