# Generated by Django 6.0.2 on 2026-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aitranslationconfig_aitranslationstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='system_prompt',
            field=models.TextField(default='Du bist ein praeziser Fachuebersetzer.\n\nUebersetze ausschliesslich die Werte des uebergebenen JSON-Objekts. Halte dich eng und vollstaendig an den deutschen Originaltext: keine kreativen Umformulierungen, keine Ergaenzungen, keine Kuerzungen, keine SEO-Optimierung und keine Erklaerungen.\n\nDie JSON-Schluessel sind technische Segment-IDs. Sie muessen unveraendert bleiben. Gib ausschliesslich ein JSON-Objekt mit exakt denselben Schluesseln und den uebersetzten Textwerten zurueck. Gib kein Markdown und keinen weiteren Text aus.\n\nHTML-Markup, technische Attribute, CSS-Klassen, Styles, URLs und IDs werden ausserhalb des Modells erhalten. Menschlich lesbare Attribute wie alt, title, aria-label und placeholder koennen als Textsegmente enthalten sein. Die Segmentwerte duerfen deshalb keine HTML-Tags enthalten. HTML-Entities innerhalb eines Segmentwerts (zum Beispiel &nbsp;) muessen unveraendert erhalten bleiben.\n', verbose_name='System-Prompt'),
        ),
    ]
