# Generated by Django 6.0.2 on 2026-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_aitranslationconfig_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitranslationstate',
            name='configuration_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Konfigurations-Hash'),
        ),
    ]
