# Generated by Django 6.0.2 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_aitranslationstate_configuration_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitranslationconfig',
            name='status_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Erfolgreiche und abgebrochene Status verschwinden danach aus der Liste. 0 deaktiviert dies.', verbose_name='Statusanzeige aufbewahren (Tage)'),
        ),
        migrations.AddField(
            model_name='aitranslationstate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ausgeblendet am'),
        ),
        migrations.AddField(
            model_name='aitranslationstate',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Aus Liste ausgeblendet'),
        ),
    ]
