# Generated by Django 6.0.2 on 2026-08-10 05:55

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_aitranslationconfig_status_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitranslationconfig',
            name='record_statuses',
            field=models.JSONField(default=ai.models.default_translation_record_statuses, help_text='Legt fest, welche aktiven, inaktiven oder archivierten Datensaetze verarbeitet werden. Datensaetze ohne eigenen Status gelten als aktiv.', verbose_name='Datensatzstatus'),
        ),
        migrations.AddField(
            model_name='aitranslationconfig',
            name='translation_areas',
            field=models.JSONField(default=ai.models.default_translation_areas, help_text='Legt fest, welche Inhalte der Uebersetzungsscan verarbeitet.', verbose_name='Uebersetzungsbereiche'),
        ),
    ]
