# Generated by Django 6.0.2 on 2026-08-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_aitranslationconfig_record_statuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITranslationGlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('source_term', models.CharField(max_length=255, verbose_name='Quellbegriff')),
                ('target_language', models.CharField(max_length=16, verbose_name='Zielsprache')),
                ('target_term', models.CharField(max_length=255, verbose_name='Verbindliche Uebersetzung')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_entries', to='ai.aitranslationconfig', verbose_name='Uebersetzungskonfiguration')),
            ],
            options={
                'verbose_name': 'KI-Uebersetzungsglossareintrag',
                'verbose_name_plural': 'KI-Uebersetzungsglossar',
                'ordering': ('source_term', 'target_language'),
                'indexes': [models.Index(fields=['configuration', 'target_language', 'is_active'], name='ai_aitransl_configu_cda47d_idx')],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'source_term', 'target_language'), name='ai_translation_glossary_unique_term')],
            },
        ),
    ]
