# Generated by Django 6.0.2 on 2026-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_translation_glossary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aitranslationglossaryentry',
            name='ai_translation_glossary_unique_term',
        ),
        migrations.RemoveIndex(
            model_name='aitranslationglossaryentry',
            name='ai_aitransl_configu_cda47d_idx',
        ),
        migrations.AddIndex(
            model_name='aitranslationglossaryentry',
            index=models.Index(fields=['target_language', 'is_active'], name='ai_aitransl_target__4d90e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='aitranslationglossaryentry',
            constraint=models.UniqueConstraint(fields=('source_term', 'target_language'), name='ai_translation_glossary_unique_term'),
        ),
        migrations.RemoveField(
            model_name='aitranslationglossaryentry',
            name='configuration',
        ),
    ]
