# Generated by Django 6.0.2 on 2026-08-20 06:02

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_global_translation_glossary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderconfig',
            options={'ordering': ('name',), 'verbose_name': 'KI-Provider', 'verbose_name_plural': 'KI-Provider'},
        ),
        migrations.AlterModelOptions(
            name='airewritejob',
            options={'ordering': ('-created_at',), 'verbose_name': 'KI-Rewrite-Job', 'verbose_name_plural': 'KI-Rewrite-Jobs'},
        ),
        migrations.AlterModelOptions(
            name='airewriteprompt',
            options={'ordering': ('name',), 'verbose_name': 'KI-Rewrite-Prompt', 'verbose_name_plural': 'KI-Rewrite-Prompts'},
        ),
        migrations.AlterModelOptions(
            name='aitranslationconfig',
            options={'ordering': ('name',), 'verbose_name': 'KI-Übersetzungskonfiguration', 'verbose_name_plural': 'KI-Übersetzungskonfigurationen'},
        ),
        migrations.AlterModelOptions(
            name='aitranslationglossaryentry',
            options={'ordering': ('source_term', 'target_language'), 'verbose_name': 'KI-Übersetzungsglossareintrag', 'verbose_name_plural': 'KI-Übersetzungsglossar'},
        ),
        migrations.AlterModelOptions(
            name='aitranslationstate',
            options={'ordering': ('status', 'updated_at', 'id'), 'verbose_name': 'KI-Übersetzungsstatus', 'verbose_name_plural': 'KI-Übersetzungsstatus'},
        ),
        migrations.AlterField(
            model_name='airewritejob',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Übernommen am'),
        ),
        migrations.AlterField(
            model_name='airewritejob',
            name='provider_response',
            field=models.TextField(blank=True, default='', verbose_name='KI-Rückgabe (roh)'),
        ),
        migrations.AlterField(
            model_name='airewritejob',
            name='status',
            field=models.CharField(choices=[('queued', 'In Arbeit'), ('ready', 'Ergebnis vorhanden'), ('applied', 'Übernommen'), ('failed', 'Fehlgeschlagen')], db_index=True, default='queued', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='batch_size',
            field=models.PositiveIntegerField(default=100, help_text='Begrenzt die Anzahl einzelner Feld-/Sprachübersetzungen je Scan.', verbose_name='Maximale Übersetzungen pro Lauf'),
        ),
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='locale_instructions',
            field=models.JSONField(blank=True, default=ai.models.default_translation_locale_instructions, help_text='JSON-Objekt mit Sprachcode als Schlüssel und Übersetzungshinweis als Wert.', verbose_name='Sprachvarianten-Hinweise'),
        ),
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='record_statuses',
            field=models.JSONField(default=ai.models.default_translation_record_statuses, help_text='Legt fest, welche aktiven, inaktiven oder archivierten Datensätze verarbeitet werden. Datensätze ohne eigenen Status gelten als aktiv.', verbose_name='Datensatzstatus'),
        ),
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='translation_areas',
            field=models.JSONField(default=ai.models.default_translation_areas, help_text='Legt fest, welche Inhalte der Übersetzungsscan verarbeitet.', verbose_name='Übersetzungsbereiche'),
        ),
        migrations.AlterField(
            model_name='aitranslationconfig',
            name='user_prompt_template',
            field=models.TextField(default='Uebersetze die Textsegmente eines einzelnen Feldes.\n\nQuellsprache: {{ source_language_name }} ({{ source_language }})\nZielsprache: {{ target_language_name }} ({{ target_language }})\nSprachvariante: {{ locale_instruction }}\n\nTextsegmente (JSON):\n{{ segments_json }}\n', help_text='Verfügbare Platzhalter: source_language, source_language_name, target_language, target_language_name, locale_instruction und segments_json.', verbose_name='Benutzer-Prompt-Vorlage'),
        ),
        migrations.AlterField(
            model_name='aitranslationglossaryentry',
            name='target_term',
            field=models.CharField(max_length=255, verbose_name='Verbindliche Übersetzung'),
        ),
        migrations.AlterField(
            model_name='aitranslationstate',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Übersetzt am'),
        ),
    ]
