# Generated by Django 6.0.2 on 2026-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_alter_aiproviderconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocumentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('system_prompt', models.TextField(default='Du strukturierst deutsche Rechtstexte fuer eine Website.\n\nDu darfst keinen Text umschreiben, ergaenzen, kuerzen oder korrigieren. Ordne jedem vorhandenen Block eine semantische Rolle zu. Die Block-IDs und ihre Reihenfolge muessen exakt erhalten bleiben.\n\nZusaetzlich darfst du Platzhalter im Format <...> mit Angaben aus der bisherigen Dokumentfassung befuellen. Eine Ersetzung ist nur erlaubt, wenn der vollstaendige Wert dort eindeutig und wortgleich vorkommt. Erfinde oder kombiniere keine Angaben. Kann ein Platzhalter nicht vollstaendig und sicher befuellt werden, lasse ihn offen und fuehre ihn nicht unter replacements auf.\n\nErlaubte Rollen fuer Textbloecke: h2, h3, p, ol_item, ul_item.\nFuer Tabellen ist ausschliesslich die Rolle table erlaubt.\n\nGib ausschliesslich ein JSON-Objekt in diesem Format zurueck:\n{"blocks": [{"id": "b0001", "role": "h2"}], "replacements": [{"id": "b0002", "placeholder": "<E-Mail-Adresse>", "value": "info@example.de", "evidence": "info@example.de"}]}\n\nJede uebergebene ID muss genau einmal und in unveraenderter Reihenfolge vorkommen. Gib kein HTML, kein Markdown und keine Erklaerung aus.\n', help_text='Steuert die Strukturierung. Unabhaengige Code-Pruefungen verhindern weiterhin Textaenderungen und unbelegte Platzhalterwerte.', verbose_name='System-Prompt')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Standard für Dokumentimporte')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'KI-Dokument-Prompt',
                'verbose_name_plural': 'KI-Dokument-Prompts',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='ai_document_prompt_single_default')],
            },
        ),
    ]
