# Generated by Django 6.0.2 on 2026-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
