# Generated by Django 6.0.2 on 2026-02-16 11:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_alter_customer_options_and_more'),
        ('orders', '0003_order_erp_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-purchase_date', '-created_at'), 'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Bestellposition', 'verbose_name_plural': 'Bestellpositionen'},
        ),
        migrations.AlterField(
            model_name='order',
            name='api_delivery_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shopware Liefer-ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='api_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Shopware Bestell-ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='api_transaction_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shopware Transaktions-ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='customer.address', verbose_name='Rechnungsanschrift'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='erp_order_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ERP Vorgangsnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Bestellstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Zahlungsart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Zahlstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bestelldatum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Verkaufskanal-ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='customer.address', verbose_name='Lieferanschrift'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Versandkosten'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Versandart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Versandstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gesamtpreis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Steuer gesamt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='api_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shopware Position-ID'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='erp_nr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ERP-Nummer'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Steuer'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gesamtpreis'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Einzelpreis'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
    ]
