# Generated by Django 6.0.2 on 2026-07-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microtech', '0022_microtechgraphqljob'),
        ('orders', '0004_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrotechOrderSyncWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('pending', 'Wartend'), ('running', 'Läuft'), ('waiting', 'Wartet auf Microtech'), ('failed', 'Fehlgeschlagen'), ('succeeded', 'Erfolgreich')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('current_step', models.CharField(blank=True, default='', max_length=64, verbose_name='Aktueller Schritt')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='Workflow-Zustand')),
                ('step_log', models.JSONField(blank=True, default=list, verbose_name='Schritt-Protokoll')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Fehler')),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='microtech.microtechgraphqljob', verbose_name='Aktueller Job')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microtech_sync_workflows', to='orders.order', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Microtech Bestell-Sync Workflow',
                'verbose_name_plural': 'Microtech Bestell-Sync Workflows',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'running', 'waiting', 'failed'))), fields=('order',), name='unique_active_order_sync_workflow')],
            },
        ),
    ]
