# Generated by Django 6.0.2 on 2026-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_microtechordersyncworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='erp_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Microtech BelegNr'),
        ),
    ]
