# Generated by Django 6.0.2 on 2026-08-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_microtech_belegnr_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtechordersyncworkflow',
            name='status',
            field=models.CharField(choices=[('pending', 'Wartend'), ('running', 'Läuft'), ('waiting', 'Wartet auf Microtech'), ('failed', 'Fehlgeschlagen'), ('succeeded', 'Erfolgreich'), ('cancelled', 'Abgebrochen')], db_index=True, default='pending', max_length=16, verbose_name='Status'),
        ),
    ]
