# Generated by Django 6.0.2 on 2026-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_microtechordersyncworkflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='microtech_export_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Für Microtech-Export freigegeben'),
        ),
        migrations.AddField(
            model_name='order',
            name='microtech_export_exclusion_reason',
            field=models.TextField(blank=True, default='', verbose_name='Ausschlussgrund Microtech-Export'),
        ),
    ]
