# Generated by Django 6.0.2 on 2026-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_microtech_export_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='erp_vorgang_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Microtech Vorgangsbezeichnung (ID)'),
        ),
    ]
