# Generated by Django 6.0.2 on 2026-09-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_erp_vorgang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='PayPal Transaktions-ID'),
        ),
    ]
