# Generated by Django 6.0.2 on 2026-09-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
            ],
            options={
                'verbose_name': 'PayPal',
                'verbose_name_plural': 'PayPal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
