# Generated by Django 6.0.2 on 2026-09-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_paypalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='PayPal ID'),
        ),
    ]
