# Generated by Django 6.0.2 on 2026-02-10 10:10

from django.db import migrations, models


def fill_erp_nr(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    for product in Product.objects.filter(erp_nr__isnull=True) | Product.objects.filter(erp_nr=""):
        if product.erp_nr:
            continue
        if product.sku:
            product.erp_nr = product.sku
        else:
            product.erp_nr = f"ERP-{product.pk}"
        product.save(update_fields=["erp_nr"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_image_tax_alter_product_options_product_erp_nr_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_erp_nr, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="erp_nr",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
