# Generated by Django 6.0.2 on 2026-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_erp_nr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('erp_nr', 'name')},
        ),
    ]
