# Generated by Django 6.0.2 on 2026-02-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_price_sales_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('product', 'sales_channel', 'price')},
        ),
    ]
