# Generated by Django 6.0.2 on 2026-02-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_name_de_category_name_en_and_more'),
        ('shopware', '0003_alter_shopwaresettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',), 'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('product', 'sales_channel', 'price'), 'verbose_name': 'Preis', 'verbose_name_plural': 'Preise'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('erp_nr', 'name'), 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('product',), 'verbose_name': 'Lagerbestand', 'verbose_name_plural': 'Lagerbestaende'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ('name',), 'verbose_name': 'Steuer', 'verbose_name_plural': 'Steuern'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Oberkategorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alternativtext'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Bildpfad'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rebate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Staffelpreis'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rebate_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Staffelmenge'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shopware.shopwaresettings', verbose_name='Verkaufskanal'),
        ),
        migrations.AlterField(
            model_name='price',
            name='special_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sonderpreis bis'),
        ),
        migrations.AlterField(
            model_name='price',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonderpreis'),
        ),
        migrations.AlterField(
            model_name='price',
            name='special_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sonderpreis ab'),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Kategorien'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short_de',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='erp_nr',
            field=models.CharField(max_length=64, unique=True, verbose_name='ERP-Nummer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Faktor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=32, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='products.image', verbose_name='Bilder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_purchase',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mindestabnahme'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kaufeinheit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Artikelnummer (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Sortierung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.tax', verbose_name='Steuer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='virtual_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Virtueller Bestand'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Steuerbezeichnung'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Steuersatz (%)'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
    ]
