# Generated by Django 6.0.2 on 2026-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='special_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sonderpreis (%)'),
        ),
    ]
