# Generated by Django 6.0.2 on 2026-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_price_special_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='shopware_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shopware Steuer-ID'),
        ),
    ]
