# Generated by Django 6.0.2 on 2026-02-24 15:43

from decimal import Decimal

from django.db import migrations


TAX_19_RATE = Decimal("19.00")
TAX_7_RATE = Decimal("7.00")
TAX_19_SHOPWARE_ID = "d391e13bdd95404a885f4ad28ea218e0"
TAX_7_SHOPWARE_ID = "be66a53eae3a49829f4a8c5959535501"


def seed_taxes_and_assign_products(apps, schema_editor):
    Tax = apps.get_model("products", "Tax")
    Product = apps.get_model("products", "Product")

    tax_19, _ = Tax.objects.update_or_create(
        rate=TAX_19_RATE,
        defaults={
            "name": "Mehrwertsteuer 19%",
            "shopware_id": TAX_19_SHOPWARE_ID,
        },
    )
    tax_7, _ = Tax.objects.update_or_create(
        rate=TAX_7_RATE,
        defaults={
            "name": "Mehrwertsteuer 7%",
            "shopware_id": TAX_7_SHOPWARE_ID,
        },
    )

    Product.objects.all().update(tax=tax_19)
    Product.objects.filter(erp_nr="950000").update(tax=tax_7)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_tax_shopware_id'),
    ]

    operations = [
        migrations.RunPython(seed_taxes_and_assign_products, migrations.RunPython.noop),
    ]
