# Generated by Django 6.0.2 on 2026-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_seed_tax_rates_and_assign_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customs_tariff_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Statistische Warennummer'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_gross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Bruttogewicht (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_net',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Nettogewicht (kg)'),
        ),
    ]
