# Generated by Django 6.0.2 on 2026-03-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_customs_tariff_number_product_weight_gross_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Reihenfolge')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.image', verbose_name='Bild')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Produktbild',
                'verbose_name_plural': 'Produktbilder',
                'ordering': ('product', 'order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('product', 'image'), name='unique_product_image_assignment')],
            },
        ),
    ]
