# Generated by Django 6.0.2 on 2026-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopware_image_sync_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shopware Bild-Sync-Hash'),
        ),
    ]
