# Generated by Django 6.0.2 on 2026-04-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_shopware_image_sync_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Attributgruppe',
                'verbose_name_plural': 'Attributgruppen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('name', models.CharField(max_length=255, verbose_name='Wert')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Wert')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Wert')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.propertygroup', verbose_name='Attributgruppe')),
            ],
            options={
                'verbose_name': 'Attributwert',
                'verbose_name_plural': 'Attributwerte',
                'ordering': ('group__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Externe Referenz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='products.product', verbose_name='Produkt')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='products.propertyvalue', verbose_name='Attributwert')),
            ],
            options={
                'verbose_name': 'Produktattribut',
                'verbose_name_plural': 'Produktattribute',
                'ordering': ('product__erp_nr', 'value__group__name', 'value__name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, through='products.ProductProperty', to='products.propertyvalue', verbose_name='Attribute'),
        ),
        migrations.AddConstraint(
            model_name='propertyvalue',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_property_value_per_group'),
        ),
        migrations.AddConstraint(
            model_name='propertyvalue',
            constraint=models.UniqueConstraint(fields=('group', 'name_de'), name='unique_property_value_per_group-name_de'),
        ),
        migrations.AddConstraint(
            model_name='propertyvalue',
            constraint=models.UniqueConstraint(fields=('group', 'name_en'), name='unique_property_value_per_group-name_en'),
        ),
        migrations.AddConstraint(
            model_name='productproperty',
            constraint=models.UniqueConstraint(fields=('product', 'value'), name='unique_product_property_assignment'),
        ),
    ]
