# Generated by Django 6.0.2 on 2026-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_propertygroup_propertyvalue_productproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Reihenfolge'),
        ),
    ]
