# Generated by Django 6.0.2 on 2026-04-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('change_type', models.CharField(choices=[('created', 'Angelegt'), ('updated', 'Aktualisiert')], default='updated', max_length=16, verbose_name='Aenderungstyp')),
                ('changed_fields', models.CharField(blank=True, default='', max_length=255, verbose_name='Geaenderte Felder')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('rebate_quantity', models.IntegerField(blank=True, null=True, verbose_name='Staffelmenge')),
                ('rebate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Staffelpreis')),
                ('special_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sonderpreis (%)')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonderpreis')),
                ('special_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Sonderpreis ab')),
                ('special_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Sonderpreis bis')),
                ('price_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='products.price', verbose_name='Preis')),
            ],
            options={
                'verbose_name': 'Preis-Historie',
                'verbose_name_plural': 'Preis-Historie',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
