# Generated by Django 6.0.2 on 2026-04-20 06:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_pricehistory'),
        ('shopware', '0004_shopwareconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('applied', 'Uebernommen')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('general_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5, verbose_name='Generelle Erhoehung (%)')),
                ('positions_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Positionen synchronisiert am')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Uebernommen am')),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_increases', to='shopware.shopwaresettings', verbose_name='Standard-Verkaufskanal')),
            ],
            options={
                'verbose_name': 'Preiserhoehung',
                'verbose_name_plural': 'Preiserhoehungen',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PriceIncreaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('unit', models.CharField(blank=True, default='', max_length=255, verbose_name='Einheit')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aktueller Preis')),
                ('current_rebate_quantity', models.IntegerField(blank=True, null=True, verbose_name='Aktuelle Staffelmenge')),
                ('current_rebate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aktueller Staffelpreis')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neuer Preis')),
                ('new_rebate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neuer Staffelpreis')),
                ('price_increase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.priceincrease', verbose_name='Preiserhoehung')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_increase_items', to='products.product', verbose_name='Produkt')),
                ('source_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_increase_items', to='products.price', verbose_name='Quellpreis')),
            ],
            options={
                'verbose_name': 'Preiserhoehungs-Position',
                'verbose_name_plural': 'Preiserhoehungs-Positionen',
                'ordering': ('product__erp_nr', 'id'),
                'constraints': [models.UniqueConstraint(fields=('price_increase', 'source_price'), name='unique_price_increase_item_per_source_price')],
            },
        ),
    ]
