# Generated by Django 6.0.2 on 2026-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_priceincrease_priceincreaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceincreaseitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neuer Preis (ed)'),
        ),
        migrations.AlterField(
            model_name='priceincreaseitem',
            name='new_rebate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neuer Staffelpreis (ed)'),
        ),
    ]
