# Generated by Django 6.0.2 on 2026-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_priceincreaseitem_new_rebate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceincreaseitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neuer Preis'),
        ),
    ]
