# Generated by Django 6.0.2 on 2026-04-21 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_priceincreaseitem_new_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='priceincreaseitem',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Aenderung am'),
        ),
        migrations.AddField(
            model_name='priceincreaseitem',
            name='last_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Letzte Aenderung durch'),
        ),
        migrations.AddField(
            model_name='priceincreaseitem',
            name='last_status_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Letzter Status'),
        ),
    ]
