# Generated by Django 6.0.2 on 2026-04-22 12:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_priceincreaseitem_last_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_api_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Legacy API-ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Legacy geaendert am'),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_erp_nr',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Legacy ERP-Nummer'),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_parent_erp_nr',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Legacy Parent ERP-Nummer'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='Oberkategorie'),
        ),
    ]
