# Generated by Django 6.0.2 on 2026-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=1000, verbose_name='Sortierung'),
        ),
    ]
