# Generated by Django 6.0.2 on 2026-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_short',
            field=models.TextField(blank=True, default='', verbose_name='Kurzbeschreibung (HTML)'),
        ),
        migrations.AddField(
            model_name='category',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SKU / Shopware-ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung (HTML)'),
        ),
    ]
