# Generated by Django 6.0.2 on 2026-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_category_description_ch_de_category_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_it_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Beschreibung (HTML)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_short_it_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Kurzbeschreibung (HTML)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it_it',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it_it',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_short_it_it',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_it_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Einheit'),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='name_it_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='name_it_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Wert'),
        ),
        migrations.AddConstraint(
            model_name='propertyvalue',
            constraint=models.UniqueConstraint(fields=('group', 'name_it_it'), name='unique_property_value_per_group-name_it_it'),
        ),
    ]
