# Generated by Django 6.0.2 on 2026-06-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_prices_without_sales_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('target', models.CharField(choices=[('shopware', 'Shopware')], db_index=True, max_length=16, verbose_name='Zielsystem')),
                ('status', models.CharField(choices=[('queued', 'Wartend'), ('running', 'Laufend'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Prioritaet')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Geaenderte Felder')),
                ('trigger', models.CharField(blank=True, default='product_save', max_length=64, verbose_name='Ausloeser')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task-ID')),
                ('attempt', models.PositiveIntegerField(default=0, verbose_name='Versuche')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max. Versuche')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Letzter Fehler')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Produkt Sync-Job',
                'verbose_name_plural': 'Produkt Sync-Jobs',
                'ordering': ('status', 'priority', 'created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'target', 'priority', 'created_at'], name='products_syncjob_queue_idx'), models.Index(fields=['product', 'target', 'status'], name='products_syncjob_product_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'queued')), fields=('product', 'target'), name='uniq_queued_product_sync')],
            },
        ),
    ]
