# Generated by Django 6.0.2 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productsyncjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsyncjob',
            name='target',
            field=models.CharField(choices=[('shopware', 'Shopware'), ('microtech', 'Microtech')], db_index=True, max_length=16, verbose_name='Zielsystem'),
        ),
    ]
