# Generated by Django 6.0.2 on 2026-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productsyncjob_target_microtech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsyncjob',
            name='target',
            field=models.CharField(choices=[('shopware', 'Shopware'), ('shopware5', 'Shopware 5'), ('microtech', 'Microtech')], db_index=True, max_length=16, verbose_name='Zielsystem'),
        ),
    ]
