# Generated by Django 6.0.2 on 2026-07-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_productsyncjob_target'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS description_short text NULL;
                    ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS factor integer NULL;
                    ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS unit varchar(255) NULL;
                    ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS min_purchase integer NULL;
                    ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS purchase_unit integer NULL;
                    ALTER TABLE products_product
                    ALTER COLUMN name DROP NOT NULL;
                    ALTER TABLE products_product
                    ALTER COLUMN description DROP NOT NULL;
                    CREATE TABLE IF NOT EXISTS products_storage (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at timestamp with time zone NOT NULL,
                        updated_at timestamp with time zone NOT NULL,
                        product_id bigint NULL UNIQUE,
                        stock integer NULL,
                        location varchar(255) NULL,
                        virtual_stock integer NOT NULL DEFAULT 0,
                        CONSTRAINT products_storage_product_id_fk
                            FOREIGN KEY (product_id)
                            REFERENCES products_product(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS price numeric(10, 2) NULL;
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'products_price'
                              AND column_name = 'amount'
                        ) THEN
                            EXECUTE 'UPDATE products_price SET price = amount WHERE price IS NULL AND amount IS NOT NULL';
                        END IF;
                    END $$;
                    UPDATE products_price
                    SET price = 0
                    WHERE price IS NULL;
                    ALTER TABLE products_price
                    ALTER COLUMN price SET NOT NULL;
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS rebate_quantity integer NULL;
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS rebate_price numeric(10, 2) NULL;
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS special_price numeric(10, 2) NULL;
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS special_start_date timestamp with time zone NULL;
                    ALTER TABLE products_price
                    ADD COLUMN IF NOT EXISTS special_end_date timestamp with time zone NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
    ]
