# Generated by Django 6.0.2 on 2026-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_ensure_product_base_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='virtual_stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Virtueller Bestand'),
        ),
    ]
