# Generated by Django 6.0.2 on 2026-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_storage_virtual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Sichtbar'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ch_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_it_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_it_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO-Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ch_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_it_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_it_it',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ch_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_it_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_it_it',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SEO-Meta-Titel'),
        ),
        migrations.AddField(
            model_name='category',
            name='sw6_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Shopware 6 ID'),
        ),
    ]
