# Generated by Django 6.0.2 on 2026-07-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_category_is_active_category_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertygroup',
            name='shopware_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Shopware Attributgruppen-ID'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='shopware_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Shopware Attributwert-ID'),
        ),
        migrations.CreateModel(
            name='ProductVariantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Technischer Schlüssel')),
                ('name', models.CharField(max_length=255, verbose_name='Shopware Parent-Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Shopware Parent-Beschreibung')),
                ('shopware_product_number', models.CharField(help_text='Technische Shopware-Artikelnummer ohne Microtech-Gegenstück.', max_length=64, unique=True, verbose_name='Shopware Parent-Artikelnummer')),
                ('shopware_id', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Shopware Parent-ID')),
                ('seo_path', models.CharField(blank=True, default='', help_text='Wird als Zielvorgabe dokumentiert; die SEO-URL wird erst im Shopware-Rollout freigegeben.', max_length=255, verbose_name='Gewünschter SEO-Pfad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('default_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_variant_families', to='products.product', verbose_name='Standardvariante')),
                ('source_categories', models.ManyToManyField(help_text='Produkte aus diesen Kategorien werden anhand ihrer Attribute als Varianten geprüft.', related_name='variant_source_families', to='products.category', verbose_name='Quellkategorien')),
                ('target_category', models.ForeignKey(help_text='Kategorie, in der nur der Varianten-Parent sichtbar sein soll.', on_delete=django.db.models.deletion.PROTECT, related_name='variant_parent_families', to='products.category', verbose_name='Shopware Zielkategorie')),
            ],
            options={
                'verbose_name': 'Variantenfamilie',
                'verbose_name_plural': 'Variantenfamilien',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='Position')),
                ('display_type', models.CharField(choices=[('text', 'Text'), ('color', 'Farbe'), ('image', 'Bild')], default='text', max_length=16, verbose_name='Darstellung in Shopware')),
                ('fallback_value', models.ForeignKey(blank=True, help_text='Beispiel: ‚Ohne Aufdruck‘ für Produkte ohne Tab-Beschriftung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_attribute_fallbacks', to='products.propertyvalue', verbose_name='Ersatzwert bei fehlendem Attribut')),
                ('property_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_family_attributes', to='products.propertygroup', verbose_name='Attributgruppe')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='products.productvariantfamily', verbose_name='Variantenfamilie')),
            ],
            options={
                'verbose_name': 'Variantenattribut',
                'verbose_name_plural': 'Variantenattribute',
                'ordering': ('family', 'position', 'property_group__name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('family', 'property_group'), name='unique_variant_attribute_per_family')],
            },
        ),
    ]
