# Generated by Django 6.0.2 on 2026-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_propertygroup_shopware_id_propertyvalue_shopware_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantfamily',
            name='synced_products',
            field=models.ManyToManyField(blank=True, editable=False, help_text='Technischer Sync-Merker. Wird automatisch gepflegt und nicht manuell bearbeitet.', related_name='synced_variant_families', to='products.product', verbose_name='Zuletzt synchronisierte Varianten'),
        ),
    ]
