# Generated by Django 6.0.2 on 2026-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_productvariantfamily_synced_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Bestand'),
        ),
    ]
