# Generated by Django 6.0.2 on 2026-07-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_storage_decimal_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optionales Bild für Shopware-Variantenoptionen mit Bilddarstellung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_values', to='products.image', verbose_name='Auswahlbild'),
        ),
    ]
