# Generated by Django 6.0.2 on 2026-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_propertyvalue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattribute',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Position'),
        ),
    ]
