# Generated by Django 6.0.2 on 2026-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_productvariantattribute_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ('group__name', 'position', 'name', 'id'), 'verbose_name': 'Attributwert', 'verbose_name_plural': 'Attributwerte'},
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Reihenfolge innerhalb der Attributgruppe und in Shopware.', verbose_name='Position'),
        ),
    ]
