# Generated by Django 6.0.2 on 2026-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_propertyvalue_options_propertyvalue_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Archiviertes Produkt',
                'verbose_name_plural': 'Produkt-Archiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archivierte Produkte sind aus der Arbeitsansicht und allen Autocompletes ausgeblendet.', verbose_name='Archiviert'),
        ),
    ]
