# Generated by Django 6.0.2 on 2026-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_archive_inactive_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sw5_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Shopware 5 ID'),
        ),
    ]
