# Generated by Django 6.0.2 on 2026-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_add_shopware5_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantfamily',
            name='description_ch_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shopware Parent-Beschreibung'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shopware Parent-Beschreibung'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shopware Parent-Beschreibung'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='description_it_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shopware Parent-Beschreibung'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='description_it_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shopware Parent-Beschreibung'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='name_ch_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Shopware Parent-Name'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Shopware Parent-Name'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Shopware Parent-Name'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='name_it_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Shopware Parent-Name'),
        ),
        migrations.AddField(
            model_name='productvariantfamily',
            name='name_it_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Shopware Parent-Name'),
        ),
    ]
