# Generated by Django 6.0.2 on 2026-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_productvariantfamily_description_ch_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sw5_id',
        ),
        migrations.AlterField(
            model_name='productsyncjob',
            name='target',
            field=models.CharField(choices=[('shopware', 'Shopware'), ('microtech', 'Microtech')], db_index=True, max_length=16, verbose_name='Zielsystem'),
        ),
    ]
