# Generated by Django 6.0.2 on 2026-09-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_context_snapshot_document_is_template_and_more'),
        ('products', '0047_remove_category_sw5_id_alter_productsyncjob_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceincrease',
            name='price_list_document',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from_price_increase', to='documents.document', verbose_name='Erzeugte Preisliste'),
        ),
        migrations.AddField(
            model_name='priceincrease',
            name='price_list_template',
            field=models.ForeignKey(blank=True, help_text='Diese Vorlage wird für das Jahresdokument der Preiserhöhung verwendet.', limit_choices_to={'document_type': 'price_list', 'is_active': True, 'is_template': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_increases_as_template', to='documents.document', verbose_name='Preislisten-Vorlage'),
        ),
    ]
