# Generated by Django 6.0.2 on 2026-09-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_priceincrease_price_list_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('vimeo_id', models.CharField(help_text='Numerische Vimeo-ID, öffentliche URL oder unlisted URL. Beim Speichern wird der Wert auf die numerische ID normalisiert.', max_length=255, unique=True, verbose_name='Vimeo-ID oder URL')),
                ('privacy_hash', models.CharField(blank=True, default='', help_text='Wird aus einer unlisted Vimeo-URL automatisch übernommen.', max_length=64, verbose_name='Vimeo Privacy-Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_posters', to='products.image', verbose_name='Vorschaubild')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('title', 'vimeo_id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('position', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='products.product', verbose_name='Produkt')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='products.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Produktvideo',
                'verbose_name_plural': 'Produktvideos',
                'ordering': ('product', 'position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('product', 'video'), name='unique_product_video_assignment')],
            },
        ),
    ]
