# Generated by Django 6.0.2 on 2026-09-29 06:25

from django.db import migrations


VIDEOS = (
    ("1018561410", "Vergleich herkömmliche Ablage und Classei", ()),
    ("502531055", "Classei Imagefilm 2021", ()),
    ("340139648", "Die wiederverwendbare Orga-Mappe Art. 20 44 51", ("204451",)),
    ("241517278", "Classata Schrank", ("730503",)),
    ("170149734", "Die Blättersicht-Mappe", ("224453", "224453P")),
    ("158880261", "Einleitung Classei Orga-Boxen", ()),
    ("152174584", "Einleitung Classei Orga-Mappen", ()),
    ("152159824", "Einleitung Classei Orga-Tabs", ()),
    ("85354439", "Die Blättersicht-Hülle", ("224553",)),
    ("81796082", "Fensterreiter verschieben", ("204462",)),
    ("56894720", "Classei-Film Kurzversion", ()),
    ("56743453", "Easy-Binding", ()),
    (
        "41014047",
        "Terminverfolgung",
        ("900043", "900044", "900047", "900048", "900049", "900050", "900052"),
    ),
    (
        "32567030",
        "Das ZPM = Zeit Projektmanagement",
        (
            "466070",
            "584470",
            "586170",
            "626026",
            "806008",
            "806108",
            "806208",
            "806308",
            "816008",
            "818009",
            "910000",
        ),
    ),
)


def seed_classei_vimeo_videos(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductVideo = apps.get_model("products", "ProductVideo")
    Video = apps.get_model("products", "Video")

    for vimeo_id, title, erp_numbers in VIDEOS:
        video, _created = Video.objects.get_or_create(
            vimeo_id=vimeo_id,
            defaults={"title": title},
        )
        for product in Product.objects.filter(erp_nr__in=erp_numbers).iterator():
            ProductVideo.objects.get_or_create(
                product=product,
                video=video,
                defaults={"position": 100, "is_active": True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_video_productvideo'),
    ]

    operations = [
        migrations.RunPython(seed_classei_vimeo_videos, migrations.RunPython.noop),
    ]
