# Generated by Django 6.0.2 on 2026-09-29 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_seed_classei_vimeo_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('package_nr', models.CharField(max_length=100, unique=True, verbose_name='Paket-Artikelnummer')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Menge')),
                ('gtin', models.CharField(blank=True, default='', max_length=32, verbose_name='GTIN')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Legacy-ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('mabox_enabled', models.BooleanField(db_index=True, default=True, help_text='Das Paket wird als Kindartikel im Mabox-Export ausgegeben.', verbose_name='Im Mabox-Export')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Pakete',
                'ordering': ('product__erp_nr', 'quantity', 'package_nr'),
            },
        ),
    ]
