# Generated by Django 6.0.2 on 2026-09-29 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaboxExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=False, verbose_name='Monatlichen Versand aktivieren')),
                ('recipient_emails', models.TextField(blank=True, default='', help_text='Eine oder mehrere E-Mail-Adressen, getrennt durch Komma, Semikolon oder Zeilenumbruch.', verbose_name='Empfänger')),
                ('send_day', models.PositiveSmallIntegerField(default=1, help_text='1 bis 28, damit der Termin in jedem Monat existiert.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Versandtag im Monat')),
                ('send_hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Stunde')),
                ('send_minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minute')),
                ('subject', models.CharField(default='Aktueller Classei-Produktexport für Mabox – {date}', help_text='Verfügbare Platzhalter: {date}, {month}', max_length=255, verbose_name='Betreff')),
                ('message', models.TextField(default='Guten Tag,\n\nanbei erhalten Sie den aktuellen Classei-Produktexport für Mabox.\n\nFreundliche Grüße\nClassei | Egon Heimann GmbH', help_text='Verfügbare Platzhalter: {date}, {month}', verbose_name='Nachricht')),
                ('from_email', models.EmailField(blank=True, default='', help_text='Leer lassen, um DEFAULT_FROM_EMAIL aus der Serverkonfiguration zu verwenden.', max_length=254, verbose_name='Absender-Adresse')),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt versendet')),
                ('last_row_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Datensätze beim letzten Versand')),
                ('last_error', models.TextField(blank=True, default='', editable=False, verbose_name='Letzter Fehler')),
            ],
            options={
                'verbose_name': 'Mabox-Export',
                'verbose_name_plural': 'Mabox-Export',
            },
        ),
    ]
