# Generated by Django 6.0.2 on 2026-09-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationcontact_smtp_host_and_more'),
        ('products', '0052_maboxexportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maboxexportsettings',
            name='from_email',
        ),
        migrations.AddField(
            model_name='maboxexportsettings',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Die SMTP-Zugangsdaten werden beim ausgewählten Ansprechpartner gepflegt.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mabox_export_settings', to='organization.organizationcontact', verbose_name='Versendender Ansprechpartner'),
        ),
    ]
