# Generated by Django 6.0.2 on 2026-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_remove_maboxexportsettings_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantattribute',
            name='expand_in_listing',
            field=models.BooleanField(default=False, help_text='Zeigt Varianten dieser Eigenschaft einzeln in Shopware-Produktlisten und Suchergebnissen.', verbose_name='In Produktlisten auffächern'),
        ),
    ]
